### ISSUE TITLE
clairification on FITS tables tutorial

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#103]
Could the rationale behind the step to create a boolean mask (line 10) and a definition of "zeroth order events" please be added?  it could also use a bit more info about what tg_m is. It becomes obivous later that tg_r and tg_d are Ra and Dec but tg_m remains mysterious. These steps and variables have implications for the last exercise and I don't get it.
@eblur

**Comment by eblur** [comment]
I'm going to work on this this week.

**Comment by kelle** [comment]
I think this has been fixed because I don't see those variable names present in the tutorial anymore.
