### ISSUE TITLE
Figure out why conda isn't generating the tutorials right

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#104]
#102 implemented machinery to use conda to auto-deploy the tutorials when something gets merged into master.  Turns out it was a good idea to start with a test branch (https://github.com/astropy/astropy-tutorials/tree/test-gh-pages) before doing it "live": for some reason travis is having issues with any astropy >1.0.4 (or maybe it's numpy?).

The trouble started in 154432ecc102c25f1bbcc8f453d448428ab719ee - before that the auto-deploy worked fine, but it was giving some spurious warnings that were fixed in 1.0.5 - so 154432ecc102c25f1bbcc8f453d448428ab719ee updated astropy to the latest stable.  However, that required updating numpy to 1.10 (because conda doesn't build newer astropys against numpy 1.9).  And with that change it's all broken.

You can see the result by looking at https://github.com/astropy/astropy-tutorials/tree/test-gh-pages (which for now I've put up at http://eteq.github.io/astropy-tutorials/ for quicker inspection).  You can see that almost all the tutorials are failing with something like `RuntimeError: module compiled against API version a but this version of numpy is 9`.

So if I'm reading that right, the baseline problem is that for some reason Travis is importing numpy 1.9 even though conda happily installed and seemingly activated 1.10.

Note that this is also happening in the regular travis builds not just the deployment, although it's not obvious because they don't actually fail.  But if you look in e.g. https://travis-ci.org/astropy/astropy-tutorials/builds/94774614 you'll see that even before deployment, the tests run like this:

```
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
---------------------------------------------------------------------------
None                                      Traceback (most recent call last)
None: None
[IPKernelApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?
```

I strongly suspect this is the same problem.

@mwcraig @bsipocz @astrofrog @adrn, anyone have any ideas?

**Comment by mwcraig** [comment]
What is the status of this? Might be a good candidate for resolving at #pyastro16

**Comment by desilinguist** [comment]
I am running into the exact same issue for my python package that dynamically renders Jupyter notebooks. See https://travis-ci.org/EducationalTestingService/rsmtool/builds/120952124

I even tried printing out all the versions of the possibly affected packages and they all seem to match my expectations so I am completely perplexed as to what's going on. I have filed an issue with the travis folks [here](https://github.com/travis-ci/travis-ci/issues/5864).

**Comment by adrn** [comment]
I think this is no longer relevant with the new build machinery.
