### ISSUE TITLE
Deprecate repository?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tutorials#109]
Now that the tutorials are in the main docs, should we deprecate this repository?

We should make sure we keep track of the existing issues and pull requests though, so we should not remove the directory yet, only mark it as being deprecated?

cc @eteq @kelle @adrn

**Comment by pllim** [comment]
:+1:

**Comment by pllim** [comment]
Oh wait... The main doc says, "Longer-form tutorials (or tutorials for affiliated packages) belong at http://tutorials.astropy.org (and can be submitted at the associated github repository)."

**Comment by bsipocz** [comment]
Also what about interpackage tutorials (if they ever got written by someone winning the infinite time lottery?. E.g. doing downloading images using astroquery, reducing them with ccdproc and performing photometry with photutils ;)

**Comment by kelle** [comment]
Yeah, I dont think we want to deprecate these. The snippets gallery is not intended to replace these longer-form tutorials.
