### ISSUE TITLE
Data files not linked in plot catalog tutorial

### ISSUE THREAD

**Issue by varunbhalerao** [astropy/astropy-tutorials#113]
Hi all,
I was recommending the http://www.astropy.org/astropy-tutorials/plot-catalog.html tutorial to my students, but it seems that the data files are not directly linked from the tutorial. Am I missing something?
-- Varun
PS: thanks for the great tutorials!

**Comment by kelle** [comment]
The files are in the repo and you are 100% correct, they don't seem to be linked from the notebook. https://github.com/astropy/astropy-tutorials/tree/master/tutorials/notebooks/plot-catalog
This needs to be fixed, thanks for pointing it out!

**Comment by kelle** [comment]
combining with #62
