### ISSUE TITLE
Change tutorials to a unified voice

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#118]
There's a mixed use of "I" vs "we" vs the 3rd-person in the tutorials.  It might be best to be uniform on this?

**Comment by tomasjames** [comment]
Happy to take this on! 

I agree, unifying it is best. Personally I prefer the use of "we" rather than "I".

**Comment by omendezmorales** [comment]
Hi, 
I'd like to participate in solving this issue. What is the current status @tomasjames ? Is there room so that  I can join? I'm new into Python + astronomy, but I've been studying the subject.
Cheers,
Orlando.

**Comment by tomasjames** [comment]
Hey @omendezmorales 

Of course, there’s always room for more open source contributors :). 

I haven’t really looked in to this in great detail to be honest, though I did settle on the 3rd person being the best compromise. I was waiting for more input before charging ahead so you joining in could help us get this fixed! 

What do you think?

**Comment by omendezmorales** [comment]
Hi @tomasjames ,
Sure the 3rd person could be a good compromise. So instead of "I", and "we", the text would read something like "the user" (he/she/it)?

I see in total 8 tutorials in[ this page](http://www.astropy.org/astropy-tutorials/). Shall we start in the appearance order there, ie. with "Analyzing UVES Spectroscopy with Astropy")? 
Cheers,

**Comment by bsipocz** [comment]
@omendezmorales and @tomasjames - Thank you for wanting to contribute. As a heads up, please note  that a big overhaul is in the works for the tutorials, see the open PRs. 
That however doesn't mean that this specific issue is already been addressed in those PRs. 

(The other question about the best unified voice is I'm not sure about, I most like we or singular they, but this is something @kelle, @adrn or @eteq needs to agree on and decide. )

**Comment by omendezmorales** [comment]
Thanks for the heads up @bsipocz ; waiting then for @kelle, @adrn or @eteq to reach consensus.

Cheers,
 
Orlando.

**Comment by kelle** [comment]
I think @lglattly took care of this and can be closed. Lauren, do you agree?

**Comment by lglattly** [comment]
Yes, this is done.
