### ISSUE TITLE
Make astropy visualization tutorial

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tutorials#119]
This was part of astropy/astropy#5570, but actually belongs here:

* [ ] Write an astropy tutorial that demonstrates the combination of SkyCoord, astroquery, reproject, and make_luptin_rgb to actually do the whole thing.
* [ ] Link to that tutorial from the docs

**Comment by kelle** [comment]
info about Lupton RBB here: http://docs.astropy.org/en/latest/visualization/lupton_rgb.html I think this would actually just be a very useful addition to the FITS-images tutorial.

**Comment by kelle** [comment]
Now part of #154
