### ISSUE TITLE
Tutorials should be tagged and labeled by focus of material

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#123]
Tutorials could be tagged by the packages and astropy-related subpackages that are used. They could also have a "focus". These are just ideas and are part of the broader need for an organizational structure.

**Comment by kelle** [comment]
the result of this probably highly granular tagging would be an index. the tags would not be prominently displayed to the users.

**Comment by adrn** [comment]
Closing this because I think we're going to strive for having a search instead
