### ISSUE TITLE
Tutorial changes are not reflected on website

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#125]
The changes to the FITS tutorials we made are not reflected on the website.

@adrn reports that travis ran fine, so is there something broken with the website? @eteq

**Comment by adrn** [comment]
There are some whack warnings in the travis build that we should address. Also not sure why it's running in python 2.7.9! Also: we probably want to run in both 2 and 3, but only deploy from, say, python 3 https://travis-ci.org/astropy/astropy-tutorials/builds/231102098 @eteq
