### ISSUE TITLE
STScI training materials

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#127]
see if it's worth co-opting any of these STScI training materails.
http://stsci-riab.github.io/riatraining/python/index.html

**Comment by emilurice** [comment]
Potentially useful content:

[Using MAST](http://stsci-riab.github.io/riatraining/archives.html#using-mast-a-k-a-the-archive): not currently AstroPy, but something similar is definitely useful (astroquery?)

[Python for Scientific Data Analysis](http://stsci-riab.github.io/riatraining/python/index.html#python-for-scientific-data-analysis): might be useful to co-opt as super-intro tutorial

[Photometry](http://stsci-riab.github.io/riatraining/photometry.html#photometry): PPT slides and Jupyter Notebook file for photometry on HST images with [photutils](https://photutils.readthedocs.io/en/stable/).

[Using DrizzlePac](http://stsci-riab.github.io/riatraining/drizzle.html): Nice tutorial for aligning & combining images (using HST data), might need re-formatting.

[Basic Spectroscopy](http://stsci-riab.github.io/riatraining/spectroscopy/index.html): LOTS of background into (physics! as a PDF) and Exercises (Jupyter notebook using COS/STIS HST data). Best adapted to be a Guide, imo.

[Using Pysynphot](http://stsci-riab.github.io/riatraining/pysynphot.html): Nice tutorial using HST data. Data required for JWST version not publicly available yet?

**Comment by pllim** [comment]
Re: PySynphot -- I am actually working on its replacement that uses Astropy models (split into https://synphot.readthedocs.io and https://stsynphot.readthedocs.io). Maybe we should wait on that one.

Also this needs updating and cleaning up but contains useful ideas -- https://github.com/spacetelescope/JWSTUserTraining2016

**Comment by emilurice** [comment]
All of these tutorials/notebooks have been added to the ["Possible Content" section of the Learn Astropy spreadsheet.](https://docs.google.com/spreadsheets/d/1JmOF82Zmrs397wLwAmmL1rgDSsvP6Z4fLMr0hV5ZIb4/edit#gid=1773165275)
