### ISSUE TITLE
Update matplotlibrc

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#141]
getting deprecation warnings in Fits-Images and Quantities

**Comment by adrn** [comment]
We should just switch to the Astropy style -- we can replace the custom matplotlibrc bit in the first cell of each notebook with:

```python
# Set up matplotlib and use a nicer set of plot parameters
from astropy.visualization import astropy_mpl_style
import matplotlib.pyplot as plt
plt.style.use(astropy_mpl_style)
```
