### ISSUE TITLE
Errors can only be ignored project-wide or by notebook

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#150]
Right now with nbsphinx, there is no way to ignore errors from a single cell. Some of the tutorials generate errors on purpose, which we want to ignore, but we also want to also be able to catch genuine failures. 

I opened spatialaudio/nbsphinx#125 to ask about this feature.

**Comment by adrn** [comment]
The feature request might even go further upstream to nbconvert. I think the easiest thing to do for now is to not have known exceptions in the tutorials - turn them into commented cell blocks, and we just have to say "this code will break..."

**Comment by eteq** [comment]
After some out-of-band discussion, @adrn convinced me that this isn't a blocker, because all the uses of exceptions in the nbs right now can be re-phrased to not raise errors/be commented out.  But this is a "nice-to-have" if nbconvert can eventually support it.
