### ISSUE TITLE
Revamp tutorials testing infrastructure

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#152]
This is a dump of the results of an infrastructure discussion of the tutorials repo from the astropy documentation sprint (which immediately followed the astropy coordination meeting 2017).  The discussion included @bsipocz @astrofrog @crawfordsm @kelle, and @adrn at various points.  The end result is that we want to:

- [x] Set a globally “pinned version” for the dependencies of all of the tutorials in the tutorials repo.  It gets updated whenever a tutorial needs an update to work.  This was a controversial element, but the consensus was this is the best solution.  If there are dissenting opinions, please leave notes in the issue here and I can elaborate more on the justification.
- [x] Need some newer/better machinery for running and generating the html of the notebooks (e.g. #151 for more discussion on a possible solution)
- [ ] We will need the following CI builds:
* (PRs/master build) Check to make sure the list of global pinned versions are *consistent* with the tutorials’ individual lists
* (PRs/master build) Check that all of the notebooks run correctly on the current globally pinned version
* (PR only) Check that the notebook(s) in that PR run against the latest *release* of the packages those notebooks require 
* (cron on master) Check that the notebooks run against latest *release* of every package that’s a dependency
* (cron on master) Check that the notebooks run against latest *dev* version of every package that’s a dependency
* (master only) Push the built notebooks to the web site

**Comment by bsipocz** [comment]
I'll come back to this in a weeks time. Ping if I don't.

**Comment by adrn** [comment]
Moving to a new, more general issue about testing the notebooks with different versions.
