### ISSUE TITLE
Improvements for the tutorial

### ISSUE THREAD

**Issue by JPVentura135** [astropy/astropy-tutorials#157]
###  Reading the data' section:

- Error statements show on the tutorial webpage due to import issues. removing these would help readability and de-clutter the page

###  Units and Constants in Astropy 

- Error generated in last cell for wavelength unit conversions:

wavelength.to(u.keV, equivalencies=u.spectral())
wavelength.to(u.Hz, equivalencies=u.spectral())
...
UnitConversionError: 'Angstrom2' (area) and 'keV' (energy) are not convertible

**Comment by kelle** [comment]
- Which tutorial is this for? Pls add that info in the title.
- Do you get these errors when you run the tutorial from the downloaded latest version of the notebook in the repo or are these errors only on the .html page?

**Comment by robmarkcole** [comment]
Theres a few errors on the [Quantities](http://www.astropy.org/astropy-tutorials/Quantities.html) tutorial

**Comment by kelle** [comment]
these have been resolved in the latest version of the tutorial:
http://astropy-tutorials.readthedocs.io/en/latest/rst-tutorials/quantities.html
