### ISSUE TITLE
Make style guide for tutorials

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#169]
For things like consistent imports, PEP8, etc. 

cc @astrofrog @bsipocz @kelle

**Comment by kelle** [comment]
This exists already and I have a branch where I'm making updates:
https://github.com/kelle/astropy-tutorials/blob/dev-contributing2/CONTRIBUTING.md

**Comment by bsipocz** [comment]
Items to add (copied over from slack):

**Imports**:
 * except the very standard (matplotlib, numpy) one, do imports around the cell they first used
 * only import things that are used (hopefully we can check for these in the tests)
 * do not use custom abbreviations, keep the name of the packages 
 * avoid importing to the main namespace, especially things that are only used once

**Outputs**
 * do not include execution numbers, etc
 * do not include output cells into commits. Squash them out if they accidentally got committed

**Comment by eblur** [comment]
Minor issues:

> do imports around the cell they first used

I don't particularly agree with this, only for the purposes of the tutorial documents.  Seeing the imports at the top of the notebook provide a sort of table-of-contents, where it is very explicit which packages are demonstrated. And this is useful even when your interested in a package that is not the target of the tutorial.  (For example, one of the tutorials uses `glob`, which is periphery to the lesson. But I noticed it right away and asked what it was.)

> do not use custom abbreviations

I think we should allow certain exceptions, e.g., `astropy.units`.  I do not want to write `units` every time, and it appears very common in the astropy community to abbreviate it to `u`

> avoid importing to the main namespace

For clarity, do you mean not using `from target.package import *` ?

**Comment by bsipocz** [comment]
>>avoid importing to the main namespace
> For clarity, do you mean not using from target.package import * ? (If yes, I agree)

Yes, or the example I saw was ``from matplotlib import rc``. This clearly better to avoid as rc should not used often, etc.

**Comment by kelle** [comment]
Please review the updated guidelines in this PR. I've included a standard import block.
https://github.com/astropy/astropy-tutorials/pull/171
