### ISSUE TITLE
Error in UVES tutorial still in rendered version

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-tutorials#172]
This tutorial has a Python 3 error and then all cells fail:
http://www.astropy.org/astropy-tutorials/UVES.html#Reading-the-data

@adrn - Looks like you fixed this 10 days ago in https://github.com/astropy/astropy-tutorials/commit/03c9af75ecd4f633fff9b2a9f16960a5063a8d7f , but the website still shows the old version.

Can you (or anyone) please deploy the new one with the fix?

**Comment by adrn** [comment]
We're in the process of completely overhauling the tutorials site and content - see #153. I temporarily disabled the website builds while we finish up the new deployment because many other things were also broken.

**Comment by kelle** [comment]
This is now resolved. 
http://astropy-tutorials.readthedocs.io/en/latest/rst-tutorials/UVES.html
