### ISSUE TITLE
Conesearch tutorial occasionally fails because of unpredictable column names

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#175]
The conesearch tutorial will sometimes fail to run because it may (behind the scenes) change the service it uses to retrieve a table, and different services use different names for RA/Dec. The tutorial assumes "RAJ2000" but it might come back as other names. We should modify the tutorial to be more careful about this.

**Comment by pllim** [comment]
You can assign this to me. I'll think about it...

**Comment by bsipocz** [comment]
I've tried to assign this, but I guess you need to be added to the tutorials team first by an admin.
