### ISSUE TITLE
Provide "Teacher documentation"

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#177]
We should add a section to the tutorials site that is similar to the developer documentation but for teachers using the material. We should give some instructions on how to make sure students are set up with the dependencies, can find the actual notebooks, etc.

**Comment by krislars** [comment]
It might be worth following the Colaboratory project that Google recently adopted.

Users can add and execute a simple `!pip install astropy`, and voila! run the tutorials from the browser.  Probably needs a Google account, prefers Chrome and all that, but might be useful for introducing new users when getting things installed on their machines is not feasible.

Here is an example of the quantities tutorial on my own drive:
[https://drive.google.com/file/d/1fTBKAUl0GgR4ESWT0fvNFFq2u_p2jtpp/view?usp=sharing](https://drive.google.com/file/d/1fTBKAUl0GgR4ESWT0fvNFFq2u_p2jtpp/view?usp=sharing
)

Also, Colab supports cell hiding as requested in #114.

Thanks to Jim Davenport who put me on to this!

**Comment by kelle** [comment]
consolidating this convo into #193
