### ISSUE TITLE
Rendering problems in Coordinates tutorial

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#180]
There are some rendering issues with the coordinates tutorial. 

* ~~~At least one footnote "If you don't know what a class method..." looks borked~~~
* Some of the links are written in RST format but need to be converted to markdown (nbconvert does the conversion for us)

**Comment by adrn** [comment]
I address the first point in the PR above, but can't figure out how to fix the links. The issue is that anything with backticks gets mangled when nbconvert exports to RST. I think the culprit here is pandoc, which is what does the actual conversion from markdown to RST. See an example of the mangled output here: http://astropy-tutorials.rtfd.io

**Comment by jimboH** [comment]
I think the problem arises from the restriction in RST format. As quoted from [https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#explicit-links](url)
> The double backquote is used to enter in verbatim mode, which can be used as the escaping character. There are some restrictions about the * and `` syntax. They
> - **can not be nested**,
> - content may not start or end with whitespace: * text* is wrong,
> - it must be separated from surrounding text by non-word characters like a space.

If  there are verbatims, italics or links used nested in the original notebook, it inevitably causes problems in the transformed RST file. Therefore, I would suggest not to use verbatims with links together in the original notebook.
