### ISSUE TITLE
Make inputs and outputs more distinct/apparent

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#188]
In the new tutorial infrastructure, inputs and outputs are difficult/inconsistent to distinguish.  This snippet from the quantity tutorial illustrates the problem:

![image](https://user-images.githubusercontent.com/346587/35880737-b8b1151c-0b4c-11e8-899d-208d05a56937.png)

The first code snippet is an input and the second is an output, but you can't tell that without already understanding what's going on.  Further down it's even *more* confusing because a `Quantity` gets rendered without a box, despite being an output of the code snippet above.

Of course it's all clear if you actually go look at the notebook... But I wonder if we want to fiddle around with the default stylings so that these things are more distinguishable? 

cc @adrn @eblur

**Comment by adrn** [comment]
I can't figure out an easy way to put `In[...]:` and `Out[...]:` into the converted cells. It looks like that is done by nbsphinx. The confusing thing is that I just realized that the nbconvert docs themselves are built with nbsphinx (e.g., [see this page](http://nbconvert.readthedocs.io/en/latest/customizing.html?highlight=input)), so before I knew that, I thought that it was easy to do with nbconvert alone. 

It looks like it may be possible to do this by modifying the template we're using to convert to rst (`astropy.tpl`) and adding a new sphinx directive to handle adding the execution count and handle the prepend (that's basically what nbsphinx does: https://github.com/spatialaudio/nbsphinx/blob/master/src/nbsphinx.py). Before going down that path, or asking @eteq to do it since he is a sphinx wizard: (1) do we actually want this, or (2) is there a simpler alternative we can think of?

**Comment by adrn** [comment]
BTW: I think it is critical to address this in *some* way before we launch.

**Comment by kelle** [comment]
I just skimmed the [Customizing nbconvert page](http://nbconvert.readthedocs.io/en/latest/customizing.html?highlight=input) and I have two ideas. 

1. Just put the In [#] Out [#] things back. This seems like the easiest option and one that I would vote for so then we can launch ASAP.

2. use a custom template to change the box color for input and output. I don't mean adding a box like they show, but changing the background color of the box the code is in. Right now, it's all this gray/purple. Maybe we use a light pink background for output. I don't see exactly how to do that in any of the examples (what's the name of the CSS element?), but it might be worth messing around with.

**Comment by adrn** [comment]
RE: 1., I tried to explain above that there is no way to easily put In[#] and Out[#]! As far as I can tell, that is done by `nbsphinx`, which `nbconvert` uses to build its docs. I don't think `nbconvert` does that natively.

**Comment by kelle** [comment]
Ok, I don't have my head wrapped around this nbconvert/nbsphinx situation  enough to help.  I'll let you and @eteq work it out.

**Comment by eblur** [comment]
Do we understand why the discrepancy is happening in the first place?

The first output is regular printed information -- and the way that it is printed does make it look like code -- so I agree with @adrn that this is critical.

The second output is LaTeX / mathjax, so does that explain why it is rendering differently?

Overall it sounds like this is a job for a sphinx wizard.  Sorry @eteq ... or can you identify some one else on the team that we can request help from?

**Comment by eteq** [comment]
Re: @eblur's

> Do we understand why the discrepancy is happening in the first place?

Definitely no to the question as posed (e.g. "understand" :wink:), but I have a *guess*: the first example is a `print` statement, which when you do in a notebook it comes in between the "input" and "output", with subtley different rendering because it's plain text.  But the `Quantity`'s are *outputs*, and the magic that makes them render using mathjax is embedded in the `_repr_latex_` method of the `Quantity` objects.  So I speculate that `nbconvert` is turning `LaTeX` objects into something quite differently from how the notebook itself does it.  Would have to experiment a bit with *other* kinds of outputs to make sure, though.

> or can you identify some one else on the team that we can request help from?

I can't think of anyone offhand, unfortunately, who wouldn't have to spend quite a while understanding the infrastructure. (Maybe @astrofrog, but he has plenty on his plate too).  So I'll give it a shot.

Before I dig too deeply, though, questions for @adrn @eblur (and maybe @kelle): what do we *want* it to look like?  You can see something closer to what it looks like when actually executed at http://nbviewer.jupyter.org/gist/eteq/abba0705394c38effb3ab30663ae9531 - there it's much clearer that the outputs are distinct whether or not you can see the `Out...` stuff.

I would tilt towards saying it should look like that, but without the In/Out bits.  (Or an In/Out *without* the number if we can figure out a way to do that.)  If we like that idea I can dig in a bit to figure out how it might be acheived.

**Comment by adrn** [comment]
I've come around to the idea that we should just put in `In[..]` and `Out[..]` to make them look like notebooks (I don't care if the execution count appears or not). I think we want to emphasize the idea that the tutorials *are* notebooks that can be run by the users, and the pages are just rendered versions of those notebooks. If we customize the style too much, new users might not immediately make that connection.

**Comment by eblur** [comment]
Agreed. We need @eteq to handle this.

However, please keep in mind that we want the solution to be simple, i.e. not so customized that it will be difficult to maintain.  Make sustainable choices. :)
