### ISSUE TITLE
Coord matching Tutorial

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#19]
cross matching two tables. - ERIK T. + Ana
@eteq

**Comment by kelle** [comment]
one of my students, Rocio, needs to do this soon. relevant module is here: http://docs.astropy.org/en/stable/coordinates/matchsep.html#astropy-coordinates-matching

**Comment by eblur** [comment]
Here it is! 
http://www.astropy.org/astropy-tutorials/Coordinates.html
