### ISSUE TITLE
gsoc 2018 - astropy tutorial

### ISSUE THREAD

**Issue by SKKSaikia** [astropy/astropy-tutorials#192]
Greetings astropy community members, I am Amartya and I am interested in building astropy tutorials in notebook. I have built one here - https://github.com/SKKSaikia/FITSview , on "FITS data :: APLpy vs Ginga" . This is just a demo tutorial and with further deep knowledge and suggestion from mentors and community members, would like to enhance and shape tutorials to its perfect form. Can you please guide me, where can I get started?

**Comment by eblur** [comment]
Hi Amarta, great to hear that you are interested!

To get started, read through the [Astropy GSoC guidelines](https://github.com/astropy/astropy/wiki/GSoC-2018-Guidelines) and follow the steps, including submitting your interest form and working on a pull request.

The next thing is to submit your example notebook as a pull request to this repo (astropy/astropy-tutorials)

We look forward to hearing more from you!
