### ISSUE TITLE
[Discussion] Colaboratory

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#194]
As mentioned by @krislars in #193 and #177, Google has a new thing, [Colaboratory](https://research.google.com/colaboratory/faq.html), for running Jupyter Notebooks in the cloud. This looks potentially very relevant to us. Maybe completed notebooks go into a drive and we add a link to the top to open in Colaboratory. Is this basically an alternative to Binder? (cc @jradavenport).

**Comment by krislars** [comment]
Thank you, @kelle !

I tried the binder link from the astropy-tutorials front page,
https://beta.mybinder.org/v2/gh/astropy/astropy-tutorials/?filepath=tutorials/notebooks
and none of the import statements work.  That's what got me headed to Colab.

**Comment by omendezmorales** [comment]
Hi @krislars and @kelle ,
When I click on the _binder_ link mentioned, indeed I get the following error message:
_Spec is not of the form "user/repo/ref", provided: "astropy/astropy-tutorials". Did you mean "astropy/astropy-tutorials/master"?_


Following the log's recommendation however, allows me to load the tutorials on binder. So the correct URL to the binder's link in the _[readme](https://github.com/astropy/astropy-tutorials/blob/master/README.rst)_ must be:

[https://mybinder.org/v2/gh/astropy/astropy-tutorials/master](https://mybinder.org/v2/gh/astropy/astropy-tutorials/master)

Now, who can update the link?

Best,

**Comment by adrn** [comment]
@omendezmorales Just fixed that bug - thanks for catching!

Looking in to the import issue now.

**Comment by adrn** [comment]
Binder import issue should be solved now - thanks for pointing that out @krislars!

**Comment by kelle** [comment]
Thinking about this a bit more...Colaboratory is essentially Google Docs for Jupyter notebooks. maybe we want to consider using Colaboratory when we're *developing* new notebooks since it allows people to work on notebooks collaboratively.  @karllark, do you want to try this out since I think you starting a new Tutorial?

**Comment by krislars** [comment]
I also happen to be a contributor to dust_extinction.  @karllark, feel free to delegate this to me!

**Comment by karllark** [comment]
@krislars, done.

**Comment by krislars** [comment]
I've been working on this.  There's lot more to be done, but here is a start:
https://drive.google.com/file/d/1zMgoGHMsWDnGLD-wtHUJheCNb2yDbqeh/view?usp=sharing

If you are logged into a google account and open the file with Colab, you can click comment in the upper right or in any cell to add a comment.

Working on this, I've found the commenting to be a little difficult to use.  Commenting is an important functionality that would be a good add to PR of notebooks in general, but I'll stay with Colab for a while and see how it matures.

**Comment by kelle** [comment]
I think Colab is great and think we should integrate into our tutorial dev workflow. It greatly lowers the barrier to entry for folks wanting to collaborate on the notebooks. (the github workflow is burdensome and not intuitive.) I've made a folder for us to put draft tutorials in: https://drive.google.com/drive/folders/1k1HnAss-pHTA3E5s9jB1OMphpBjQ-U7l
