### ISSUE TITLE
How to implement dynamic search in new website? 

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#203]
We have some great mockups for a new website (#200) and a great new sphinx infrastructure (#153) but how will they work together? What is the actual code or plugins which can be used to make the dynamic search work within the sphinx generated pages?

**Comment by MananAgarwal** [comment]
Hey @kelle,
Glad that you liked the mockups. I looked into the integration with Sphinx infrastructure. Here are two options that we can consider:

- [sphinx-bootstrap-theme](https://github.com/ryan-roemer/sphinx-bootstrap-theme): This is a configurable, extensible and mobile-friendly theme that integrates **Bootstrap** CSS/JS framework with various layout options. 

- Sphinx has a feature that allows us to create [custom themes](http://www.sphinx-doc.org/en/master/theming.html). It provides support for changing the appearance of its HTML output.

For the implementation of filters, we can use **tags** for different categories like 'material type', 'Astropy packages', 'non-astropy packages' etc.

The dynamic search can be implemented using either of these options: 

- Using the [get_search_results()](http://www.sphinx-doc.org/en/stable/web/quickstart.html) function of the WebSupport class in the Sphinx API. It takes a query as an argument and returns the search results along with the context. An extended version of this, are [SearchAdapters](http://www.sphinx-doc.org/en/stable/web/searchadapters.html) which are implemented using BaseSearch class. These provide for more customized search results. 

- Using a library, [Whoosh](https://bitbucket.org/mchaput/whoosh/wiki/Home). It is a fast, featureful full-text indexing and searching library implemented in pure Python that allows us to easily add dynamic search features to websites.

**Comment by littlewonder** [comment]
@kelle
Sorry for getting on this late. I was sick and recovery took quite some time. Apologies :-)

> What is the actual code or plugins which can be used to make the dynamic search work within the sphinx generated pages?

I'd suggest using Sphinx inbuilt JavaScript utility for the full-text search, [searchtools.js](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/searchtools.js_t). Pytorch uses the same for searching through its [Sphinx generated docs](http://pytorch.org/docs/0.3.1/).

**Comment by eblur** [comment]
Hi all, this is a reminder to please put your landing pages and at least the beginning of your implementation into a pull request so that we can see the source code.

Also let us know when you have opened your GSOC application on the GSOC website. We will be able to see them and could give you feedback.

See the [Astropy GSOC 2018 Guidelines](https://github.com/astropy/astropy/wiki/GSoC-2018-Guidelines) page for more info.

**Comment by kelle** [comment]
Thank you for your well thought out proposals! Now that they are in, I'm gonna close this issue.
