### ISSUE TITLE
Try to get the "old" page to do a 301-style redirect

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#204]
Having just rolled out the readthedocs version of the tutorials (and updated http://tutorial.astropy.org to point there), @eblur pointed out that http://www.astropy.org/astropy-tutorials still points to the "old" version.  (That's the same as the `gh-pages` branch of *this* repository - https://github.com/astropy/astropy-tutorials/tree/gh-pages .) Responding to that, I pushed up a quick update that turns http://www.astropy.org/astropy-tutorials/index.html into a redirect page to point to the new tutorials.

The *problem* is: HTML redirects do not redirect search engines.  So (I think) Google will continue to get  http://www.astropy.org/astropy-tutorials/index.html as the top hit for "astropy tutorials" instead of the new page. The standard solution to this is to use a server-side 301 redirect... But we don't have direct control of the server because it's on GitHub Pages.

Googling (ironically) leads to this solution: https://help.github.com/articles/redirects-on-github-pages/ .  That's not quite what we want because it requires that the "to" page be on Github Pages.  More googling leads to this: https://github.com/jekyll/jekyll-redirect-from#redirect-to, which should work as long as GitHub has that plugin turned on.

So the solution at the end here needs to be tested.  I haven't had a chance to do that, but someone else can given what I've written  (maybe @adrn? or @granttremblay since this is web-site related?) here in case I don't have time for a while.

**Comment by kelle** [comment]
It looks like google is still finding specific tutorials. SHould we redirect all the old pages? Or add a banner of some kind to the top of them? I vote for redirecting everything, even if we need to do it by hand for the ~10 old tutorials.

**Comment by kelle** [comment]
I think this is pretty high priority. Maybe I will work on it in the afternoon...just add hard link to the top of the pages. Maybe I can add also add in the redirect info in the header so the search engines learn?

**Comment by kelle** [comment]
@adrn @eteq I'd like to fix this this afternoon. I'm gonna find you to figure out where the HTML files are that live on astropy.org. And to figure out the best meta tags to put in. 
```
<meta http-equiv="refresh" content="2; URL=http://<new tutorial page>">
<meta name="keywords" content="automatic redirection">

**Comment by adrn** [comment]
I think this is no longer relevant!
