### ISSUE TITLE
WCS error in UVES tutorial

### ISSUE THREAD

**Issue by emilylurice** [astropy/astropy-tutorials#206]
`wcs = WCS(header) `
results in 
NameError: name 'WCS' is not defined

**Comment by hamogu** [comment]
There is a comment in #207 indicating that this may not be a real problem and may have been caused by and old astropy version. Should this issue be closed?

**Comment by adrn** [comment]
Looking at the notebook, and seeing that the builds are working, I don't think this is a bug in the notebook itself. Is it possible you tried executing a later cell before running the first few? In any case, please reopen if you disagree @emilylurice !
