### ISSUE TITLE
Make it possible to set the kernel used in `make html`

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#209]
Right now if you run `make html` (the only convenient way to build not on RTD), the nbconvert machinery uses some default kernel (I *think* based on whatever name is in the notebook).  Often that's not desirable - for example I have a special conda environment just for the tutorials, and probably other users will too to various degrees.

So there should be some way to set what kernel is being used to execute the tutorials when you do `make html`. It's already possible in the `scripts/convert.py` script using the ``--kernel-name`` option.  So we just need to get that into the `Makefile` machinery (which I think goes by way of `conf.py` in Sphinx to actually do the build).  Probably the easiest thing is to use an environment variable trick - like ``TUTORIALS_KERNEL_NAME="blah" make html``.  But there might be some clever way to use the "current" environment, which might be just as good?

**Comment by adrn** [comment]
I think this was solved with #244
