### ISSUE TITLE
Have cell timeout errors point to which cell is the problem

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#211]
Really long-running cells eventually timeout on RTD - see https://readthedocs.org/projects/astropy-tutorials/builds/6923426/ for a log with an example of this.  

The problem is, the logs there don't report anything about *which* cell is the problem.  We should try to figure out how to catch those errors and report some more information about them.

cc @adrn

**Comment by adrn** [comment]
Going to close this because the build machinery has changed significantly and we now can see which cells timeout with nbcollection!
