### ISSUE TITLE
Just a little contribution

### ISSUE THREAD

**Issue by sebauri** [astropy/astropy-tutorials#217]
I was trying you tutorial and I have an issue using python2 in the coordinates notebook tutorial. 

Anyway I resolved changing the inicial cell for this:

# Python standard-library
try:
    # For Python 3.0 and later
    from urllib.request import urlretrieve #original line
    from urllib.parse import urlencode   #original line
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib import urlretrieve
    from urllib import urlencode

The everything well :D

Cheers!

**Comment by pllim** [comment]
I am not sure what is the Python 2 support policy over here but as of `astropy` 3.0, Python 2 is no longer supported. I recommend switching to Python 3. FYI.

**Comment by sebauri** [comment]
Thank you, I have python2 by default in my notebook I will switch to Python3
