### ISSUE TITLE
Edit on github link broken?

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy-tutorials#218]
The edit on github link at http://www.astropy.org/astropy-tutorials/FITS-header.html takes me to https://github.com/astropy/astropy-tutorials/tree/master/tutorials/FITS-header, which is a 404.

**Comment by bsipocz** [comment]
I would suggest to turn it off as a short term workaround until someone gets there and fixes it.

**Comment by kelle** [comment]
That page is deprecated and we need to figure out the redirect as described in #204
