### ISSUE TITLE
"Advanced" package management: Conda environments

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#221]
This might be a useful resource:
https://astroconda.readthedocs.io/en/latest/

Add a documentation page and youtube video about making environments in Conda. A useful example that many will want to know is how to set up a Python 2 environment.

Also give options for environment management within jupyter notebook.

**Comment by bsipocz** [comment]
👍 

I don't think there should be any effort put into python2 materials as it's already in the sunsetting period, more and more packages are dropping support and it will completely became unsupported by the python dev at the end of 2019.

**Comment by eblur** [comment]
These are on my personal github page now:
https://github.com/eblur/how-to
