### ISSUE TITLE
Ingest STAK content

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#224]
Do we want to consider ingesting some of the material developed by the [STScI STAK project](http://stak-notebooks.readthedocs.io/en/latest/index.html) into astropy tutorials and/or examples? There are a LOT of standard astro & IRAF tasks displayed there.

@saogaz @eteq

**Comment by pllim** [comment]
@saraogaz ?

**Comment by SaOgaz** [comment]
I don't see a problem with doing this in some capacity.  I was waiting on RTD the fix something before doing a more public release, which is now done. So hopefully that will happen this week.

**Comment by pllim** [comment]
STAK is no longer actively developed.
