### ISSUE TITLE
Some tutorials missing learning goals

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#254]
Could the authors please provide a set of learning goals (bulleted list of a few key takeaways) for:
* Viewing and manipulating FITS images (author @eblur)
* Viewing and manipulating FITS tables (author @eblur)
* Using Astropy Quantities for astrophysical calculations (authors Ana Bonaca, @eteq)
* Make a plot with both redshift and universe age axes using astropy.cosmology (author Neil Crighton)
* Analyzing UVES Spectroscopy with Astropy (@hamogu @migueldvb)
* VO Simple Cone Search Tutorial (@pllim)

**Comment by kelle** [comment]
addressed by #380
