### ISSUE TITLE
Add link to STScI notebook style guide in the contributing docs

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#256]
Add a link to the Space Telescope notebook style guide into Contributing.md

https://github.com/spacetelescope/style-guides/blob/master/guides/jupyter-notebooks.md

**Comment by agarwalrounak** [comment]
HI @eblur! I guess this issue is identical to #284 and PR #326 solves this issue as well. I have updated the PR definition accordingly. You can close this.
