### ISSUE TITLE
CircleCI build failing on missing catalog in vo conesearch tutorial

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#265]
See the build failure here:
https://circleci.com/gh/astropy/astropy-tutorials/131

@pllim any idea why "The USNO-A2.0 Catalogue (Monet+ 1998) 1" is now invalid?

**Comment by omendezmorales** [comment]
Hi Adrian,
I've looked into the /artifacts  /
<https://circleci.com/gh/astropy/astropy-tutorials/131#artifacts/containers/0>tab
in the URL below, and the explanation is that the catalogue /is gone:

/

MissingCatalogTraceback (most recent call last)
<ipython-input-12-bfd7c6bcdf92> in <module>() 1 result =
conesearch.conesearch( ----> 2c, 0.1 * u.degree, catalog_db='The
USNO-A2.0 Catalogue (Monet+ 1998) 1')
~/project/venv/lib/python3.6/site-packages/astroquery/vo_conesearch/conesearch.py
in conesearch(center, radius, verb, catalog_db, pedantic, verbose,
cache, timeout, query_all) 219 remote_db =
vos_catalog.get_remote_catalog_db( 220 service_type, cache=cache,
verbose=verbose) --> 221catalog = remote_db.get_catalog(catalog) 222 url
= catalog['url'] 223 else:
~/project/venv/lib/python3.6/site-packages/astroquery/vo_conesearch/vos_catalog.py
in get_catalog(self, name) 249 """ 250 if name not in self._catalogs:
--> 251raise MissingCatalog("No catalog '{0}' found.".format(name)) 252
253 return VOSCatalog(self._catalogs[name]) MissingCatalog: No catalog
'The USNO-A2.0 Catalogue (Monet+ 1998) 1' found.


------------------------------------------------------------------------
Don't know however how to put it back... @pllim <https://github.com/pllim>?

Regards,

------------------------------------------------------------------------




Adrian Price-Whelan wrote:

**Comment by pllim** [comment]
Services get removed sometimes. Sigh, I guess I'll have to modify the tutorial again but I won't have time in the next few weeks. Thanks for the notice.

**Comment by pllim** [comment]
`The USNO-A2.0 Catalogue (Monet+ 1998) 1')` works for me locally. Are you sure it is consistently failing? Intermittent interruptions are common and are beyond the control of Astroquery.

If it works for you locally but never works in CircleCI, then it is something wrong with CircleCI service.

**Comment by kelle** [comment]
I think this can be closed. This tutorial is not passing tests right now, but for different reasons...
