### ISSUE TITLE
Make button on new Learn Astropy website for link to contributing.rst

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#267]
We would like a button near the top of the Learn Astropy website to link to the Contributing.rst page.

See the "Example Gallery" on the astropy.org page for an example of button styles:
http://www.astropy.org/

The button should link to wherever the Contributing.rst page lives in the Learn Astropy website infrastructure. The current page is on readthedocs, here:
https://astropy-tutorials.readthedocs.io/en/latest/contributing.html#contributing-page

**Comment by MananAgarwal** [comment]
"Contribute" button added on the home page in the pull request #247 commit 89fa556
