### ISSUE TITLE
Get the circle ci test to fail when sphinx builds fail

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#268]
Right now `make html` yields 18 warnings - surely a sign of problems that need fixing in the built docs.  However, circle-ci is happily passing.  I think this is because at some point we removed the machinery that checks the sphinx build (from the helpers) in favor of giles... But giles doesn't appear to return a failure if the sphinx build has warnings.

@adrn - did I miss the boat on this and it was intended?  Or an oversight?

**Comment by kakirastern** [comment]
Hi @eteq... I think I have fixed the warning about the missing favicon link in a recent PR. I have used `make html` to build the docs of "Learn Astropy", and everything seems alright now. Could you please check the latest version and confirm that there are still any warnings?

**Comment by adrn** [comment]
No longer relevant
