### ISSUE TITLE
make html and python convert.py <path> are no longer consistent

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#270]
Not urgent, but a middle-term todo: at one point it was (mostly?) the case that if you did `python scripts/convert.py <path>` it generated the same rst files/etc that `make html` did.  That made debugging a lot easier.  That seems to no longer be the case, I think because there's now more configuration in the `conf.py` instead of `convert.py`.  Should make this easier/more consistent somehow.

**Comment by adrn** [comment]
Going to close this because the build machinery is about to change, and I've already disabled the circleci builds! (see #495)
