### ISSUE TITLE
CI checks failing on FITS-cubes

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#277]
@bsipocz @adrn CircleCI and Travis are periodically failing checks on FITS-cubes due to download time-outs. This is messing with our ability to merge PRs that are unrelated to FITS-cubes.

Currently failing CircleCI and Travis on PR #248 
Currently failing Travis on PR #247 

Should we pull out FITS-cubes until we find a viable solution for a large-file problem?

**Comment by bsipocz** [comment]
if nothing happens until then, please remind me about this next week f2f

**Comment by eblur** [comment]
See PR #288 and Issue #289 

I'll close this issue when FITS-cubes is removed from the master branch.

**Comment by adrn** [comment]
It's moved to the quarantine!
