### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#283]
Tutorials are not being loaded.

Unable to scroll properly

**Comment by MananAgarwal** [comment]
Somehow it's not able to find "filterTutorials".
As the mechanism used to generate the tutorials page is the same as for the search, I tried searching for the filterKeywords and found that all but "filterTutorials" is working. Even "filterTutorial" (i.e. dropping the 's') works.

_filterCoordinates_
<img width="1660" alt="screenshot 2018-12-06 at 10 10 29 am" src="https://user-images.githubusercontent.com/24625562/49562517-e382f100-f941-11e8-8afc-3f0a977984ba.png">

_filterTutorial_
<img width="1579" alt="screenshot 2018-12-06 at 10 09 07 am" src="https://user-images.githubusercontent.com/24625562/49562524-e847a500-f941-11e8-96c3-e815482cf06f.png">

_filterTutorials_
<img width="1680" alt="screenshot 2018-12-06 at 10 07 53 am" src="https://user-images.githubusercontent.com/24625562/49562529-ebdb2c00-f941-11e8-92d8-0d4d0daabeb1.png">

The only difference that I could find between filterTutorials and other keywords is this:
1.
<img width="742" alt="screenshot 2018-12-06 at 10 25 40 am" src="https://user-images.githubusercontent.com/24625562/49562411-7cfdd300-f941-11e8-963d-a956b9232108.png">
2. I have written a custom placard generator for "filterTutorials" keyword.

I don't think either of them should have created a problem. How can I test things on the final build?

**Comment by eteq** [comment]
Alright, #297 is good so it's looking all set to me.  Going to close this issue.

Longer-term we may want to debug RTD, but we can do that at our leisure while the tutorials page is up and running.
