### ISSUE TITLE
Update FITS-cubes (in quarantine)

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#289]
The FITS-cubes tutorial is currently in the `quarantine` branch.

Issues that need to be addressed:

* cube.quicklook() raised errors with matplotlib. May need updates to make it compatible with spectral-cube version 0.4.3. The file was made with version 0.4.1

* We need to find a file that is less than a 200 MB download.

**Comment by eblur** [comment]
Opened an issue in spectral-cube repo:
https://github.com/radio-astro-tools/spectral-cube/issues/511

**Comment by eblur** [comment]
@kakirastern is working on this

**Comment by kakirastern** [comment]
Thanks @eblur. Am looking into the issue, and will open a PR regarding it soon.

**Comment by kakirastern** [comment]
I have found the directory containing the original data cube used in the tutorial, at the URL: [http://cdsarc.u-strasbg.fr/ftp/J/A+A/594/A116/CUBES/GAL/TAN/](http://cdsarc.u-strasbg.fr/ftp/J/A+A/594/A116/CUBES/GAL/TAN/), and have checked that file sizes listed there are all greater than 200 MB.

**Comment by kakirastern** [comment]
So finding a smaller replacement file from the same source is not an option. Next, will attempt to reduce chosen data cube used sample in file size with rebinning, perhaps using SciPy... (Example: [https://scipy-cookbook.readthedocs.io/items/Rebinning.html](https://scipy-cookbook.readthedocs.io/items/Rebinning.html)).

**Comment by kakirastern** [comment]
> Issues that need to be addressed:
> 
> * cube.quicklook() raised errors with matplotlib. May need updates to make it compatible with spectral-cube version 0.4.3. The file was made with version 0.4.1
> * We need to find a file that is less than a 200 MB download.

Further responses: 
* cube.quicklook() seems to be working fine with Matplotlib v3.0.2 and Spectral-Cube v0.4.3 now... so will move on the other parts of tutorial. 
* It takes more than 10 minutes to download the original cube, so alternative route of downloading it first then read it from computer would also not be recommended.

**Comment by kakirastern** [comment]
Opened a PR to address this Issue.

**Comment by kakirastern** [comment]
So the Google CoLab link for the updated version of the tutorial can be found at [https://colab.research.google.com/drive/1dX05QJ0aOyVJN9ZWWP2-2CCnneW1ew8o](https://colab.research.google.com/drive/1dX05QJ0aOyVJN9ZWWP2-2CCnneW1ew8o) .
