### ISSUE TITLE
Re-brand this repo "Learn"?

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#299]
This repo now hosts the code for Learn Astropy and is therefore broader than just astropy tutorials. We need to make some decisions about how we want to organize things now and in the future when the guides are ready. For example, do we want to have the guides and tutorials all live in this repo with the website code? Or do we want to have a new website for the website build and have the tutorials and guides in a separate place?

**Comment by kakirastern** [comment]
Followed up in Issue #316 ?...

**Comment by kelle** [comment]
I think we've decided that everything lives here and this can be closed. @adrn do you agree?

**Comment by kelle** [comment]
Should we actually change the name of the repo? https://help.github.com/en/articles/renaming-a-repository
