### ISSUE TITLE
Decide the long-term plan for the canonical deploy location and update docs appropriately

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#301]
#283 revealed some of the issues with using RTD as a deploy location for the tutorials, so we are now back to gitghub pages. This is not necessarily a bad turn of events, but we should make a decision whether we want to try to get RTD working again. And once we've decided we should document the choice.  And relatedly, if we are *not* going with RTD we should consider whether the dev docs should just turn off RTD and have the canonical dev docs be the ones built with the tutorials.

Some considerations (in no particular order):
* Github pages makes the URL more natural: http://www.astropy.org/astropy-tutorials (which can't be easily done with RTD, although there's probably *some* way to get it on the astropy.org domain?)
* RTD will be easier to "tag" specific versions
* RTD might be easier for translations (if we ever get to that?)
* RTD may be very hard to get working (i.e. #283)
* Should we consider using [netlify](https://www.netlify.com/), which is basically a "better" github pages (i.e., does a lot more things) - might help with the versioning?

cc @adrn (and @kelle @eblur, although maybe you don't care that much since this is decidedly "infrastructure")

**Comment by adrn** [comment]
I'm making the call that the benefits don't outweigh the negatives (on getting RTD working), so let's just stick with gh-pages (see #319)

**Comment by adrn** [comment]
No longer relevant.
