### ISSUE TITLE
New tutorial: computing Galactic orbits with Gaia + gala

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#302]
I wanted to try out the new colab workflow, so here is a new tutorial that highlights the affiliated package `gala` to do some orbit integration with Gaia data:
https://colab.research.google.com/drive/1DoU4hyLVbpC7_ms8vWGcC5lrKy61_Fbc

**Comment by eblur** [comment]
@rkiman can you please review the content for clarity? :)

Some immediate observations:
* Learning Goals
* An exercise at the end

**Comment by adrn** [comment]
Feel free to edit the colab notebook directly!

**Comment by adrn** [comment]
Note: I added learning goals, added two exercises and addressed the comments @kelle left in the colab notebook. Does someone else want to take a look at the content? @rkiman ?

**Comment by kakirastern** [comment]
Hi @adrn, is it okay for me to help edit/proofread the content if desired?

**Comment by adrn** [comment]
@kakirastern sure! Please leave comments rather than editing the content directly.

**Comment by kakirastern** [comment]
@adrn Cool, will proofread and leave comments where appropriate within the next few days.

**Comment by adrn** [comment]
I think I've addressed all of @rkiman's comments! Any other comments?

**Comment by kakirastern** [comment]
@adrn Give me say one more day to go over the tutorial... Will get back to you soon

**Comment by kakirastern** [comment]
Sorry about the delay... I have reviewed the tutorial and left some comments in Colab. Hope they are useful in shaping the tutorial further.

**Comment by adrn** [comment]
Thanks - these were useful comments. Thanks everyone for reading and commenting - I'm happy with this tutorial now, and will move it from Colab into an official PR.

**Comment by adrn** [comment]
(Please leave further comments in #342)
