### ISSUE TITLE
Hide the "q=filterTutorials" when showing all the tutorials

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#304]
Right now to get all the tutorials, the URL has to end with the query `?q=filterTutorials`.  That's a bit ugly, and is an implementation detail leaking out into the user-space.  It also has the (admittedly minor) side-effect that if the text "featureTutorials" is in any notebook it gets highlighted. We should figure out how to have that not be necessary - I think this is probably just a javascript tweak to make the "no query string" default be equivalent to "filterTutorials".  But I haven't looked in detail, so @MananAgarwal might have more context/ideas.

**Comment by eteq** [comment]
I looked into this a bit more but am stuck on one thing: I don't understand which js function actually populated the placard.  I was hoping to just set a way to give it a "default value" (which would be page-specific) if there is *no* query string. But I cannot the initial "starting point" on the tutorials page that populates the placards.  @MananAgarwal maybe you can advise?

**Comment by MananAgarwal** [comment]
"makeSearchSummary" receives the search query as "keywords" and "hlwords" (i.e highlight words).
https://github.com/astropy/astropy-tutorials/blob/82379f59dbd246b80dbc557e4d647ea9f2b699cf/tutorials/themes/tutorials-theme/static/searchtools.js#L770

This checks for "filterTutorials" and then creates the contents for the placards on the tutorial page.
https://github.com/astropy/astropy-tutorials/blob/82379f59dbd246b80dbc557e4d647ea9f2b699cf/tutorials/themes/tutorials-theme/static/searchtools.js#L790

The final HTML element with the populated placards
https://github.com/astropy/astropy-tutorials/blob/82379f59dbd246b80dbc557e4d647ea9f2b699cf/tutorials/themes/tutorials-theme/static/searchtools.js#L843
