### ISSUE TITLE
Why not use nbsphinx?

### ISSUE THREAD

**Issue by mgeier** [astropy/astropy-tutorials#313]
I'm quoting http://www.astropy.org/astropy-tutorials/dev.html#why-not-use-nbsphinx:

> In particular, there is no supported way to modify the template file that controls the output RST file that gets generated from each notebook; we want to be able to modify the template so we can add the links mentioned above.

First of all, there are no links mentioned above that paragraph.

Second, to create those links you are (not) talking about, `nbsphinx` has a feature since version 0.3.0 that is intended mainly for such cases: `nbsphinx_prolog` and `nbsphinx_epilog`.

For detailed documentation see https://nbsphinx.readthedocs.io/en/0.4.1/prolog-and-epilog.html.

It is still correct that you are not supposed to modify the template (because it is merely an implementation detail), but I guess this isn't necessary anymore.

> it doesn’t support all of the features we want

If there are any other missing features, feel free to suggest them at https://github.com/spatialaudio/nbsphinx/issues. Pull requests are of course also welcome.

**Comment by adrn** [comment]
We no longer use sphinx, so this is not relevant.

**Comment by mgeier** [comment]
Thanks for the update @adrn.

The bottom of the linked page still says "Created using Sphinx 2.4.4.".

Is this page outdated?
Will it be replaced?

Even if you don't use Sphinx (which is totally fine, it's your choice!), my points above are still valid, aren't they?

Again, I'd love to hear some details about what you are missing from `nbsphinx`, so that I can hopefully improve it.
