### ISSUE TITLE
learn.astropy.org redirects instead of being the domain

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#316]
learn.astropy.org redirects to astropy.org rather than staying as the domain.

**Comment by eblur** [comment]
Note that Google searching "Astropy tutorials" will give tutorials.astropy.org as the first hit

**Comment by kelle** [comment]
- I don't think this is super high priority but it would be nice. 
- I think higher priority is that we want the first search engine hit for Astropy Tutorials to be "learn.astropy.org". And we want to deprecate/delete "tutorials.astropy.org" url.

**Comment by kakirastern** [comment]
Think the **A Record** has to be updated to "learn.astropy.org" instead of setting it as a **CNAME** as the current state of affairs in order to effect this change.

**Comment by eblur** [comment]
@eteq any thoughts?

**Comment by adrn** [comment]
Solved!

**Comment by kakirastern** [comment]
Yay! This is so cool... I just tried entering "learn.astropy.org" into my browser search field, and it works!
