### ISSUE TITLE
tutorial versioning/testing

### ISSUE THREAD

**Issue by migueldvb** [astropy/astropy-tutorials#32]
It would be useful to have a list of astropy versions for which  each tutorial is known to work. I have tried to modify one of the tutorials to work on the current stable release thinking that it was written for a previous release, before I noticed that it runs fine with the latest development version. Maybe not very important now that things are still changing but at some point it would be good to show in the tutorial index which astropy versions have been tested and are supposed to run without problems.

**Comment by adrn** [comment]
We have a plan! See: https://docs.google.com/document/d/17cLbhgd7Ownb-Uo7EmFHgI1U3lqQWWL77szEAnZwyv0/edit

**Comment by bsipocz** [comment]
I think this can be closed and move the discussion to https://github.com/astropy/astropy-tutorials/issues/152 that details out the grand plan to for testing (based on the notes linked above).

**Comment by adrn** [comment]
Sounds good!
