### ISSUE TITLE
"Using scipy.integrate" tutorial has some weirdness in the display

### ISSUE THREAD

**Issue by ceb8** [astropy/astropy-tutorials#320]
"[Using scipy.integrate](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html)" has a few problems that show up in the website display, but that look fine in the actual notebook:
- The cell that contains imports in the [summary section](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html?highlight=filtertutorials#summary) is not displaying at all
- The links in the [How to simulate actual observations](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html#how-to-simulate-actual-observations) section are showing their raw markdown instead of looking like proper links (Also in the [Integrating Using Gaussian Quadrature](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html#integrating-using-gaussian-quadrature) section)
- In the [Challenge Problems](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html#challenge-problems) section some of the latex is rendered but some shows up as raw latex
- The "Download Tutorial Notebook" and "Interactive Tutorial" buttons at the top of the notebook work, but the ones at the bottom do not.

**Comment by kakirastern** [comment]
Hi @ceb8, 
Yes, I see the problems showing up in my web browser ("Chrome") too, but they indeed don't show up in the actual downloaded notebook. Will follow up on the Issue by updating the notebook in a new PR soon, if that fixes that problems...

**Comment by kakirastern** [comment]
Opened PR #330 to deal with issues raised here.

**Comment by kakirastern** [comment]
Have dealt with the following issues: 
> * The cell that contains imports in the [summary section](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html?highlight=filtertutorials#summary) is not displaying at all
> * The links in the [How to simulate actual observations](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html#how-to-simulate-actual-observations) section are showing their raw markdown instead of looking like proper links (Also in the [Integrating Using Gaussian Quadrature](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html#integrating-using-gaussian-quadrature) section)
> * In the [Challenge Problems](http://www.astropy.org/astropy-tutorials/rst-tutorials/units-and-integration.html#challenge-problems) section some of the latex is rendered but some shows up as raw latex

Have opened PR #334 to reformat the list used for the questions in the "Challenge problems" (or last) section. 

The new Learn Astropy is still in development, and we note that the following has not been addressed yet: 
> * The "Download Tutorial Notebook" and "Interactive Tutorial" buttons at the top of the notebook work, but the ones at the bottom do not.

But for now the last item might be out of the scope of the individual tutorial per se, and has more to do with website architecture. May be dealt with at a later time.
