### ISSUE TITLE
Tutorial related to data cube but not linked to the datacube keyword

### ISSUE THREAD

**Issue by kakirastern** [astropy/astropy-tutorials#322]
Hi. I found a data-cube related tutorial which has yet to be linked to the "data cubes" keyword, which can be accessed via the URL: [http://www.astropy.org/astropy-tutorials/rst-tutorials/quantities.html?highlight=data%20cubes](http://www.astropy.org/astropy-tutorials/rst-tutorials/quantities.html?highlight=data%20cubes). 

In the tutorial, of particular relevance is the section on ["Setting up the data cube"](http://www.astropy.org/astropy-tutorials/rst-tutorials/quantities.html?highlight=data%20cubes#setting-up-the-data-cube), so I think it may not be a bad idea to open an Issue regarding it.

**Comment by kakirastern** [comment]
@MananAgarwal Are you working on something related to this issue? Just wanted to double check with you first.

**Comment by MananAgarwal** [comment]
@kakirastern The way filter functionality works right now is by linking a tutorial to all the keywords mentioned in the "Keywords" section of the tutorial. Like in this case, only units, matplotlib and radio astronomy are mentioned as keywords in quantities.html
We simply need to add "data cubes" to this list to link it with "data cubes" keyword

**Comment by kakirastern** [comment]
Hi @MananAgarwal . Great! Then it is easy to fix then. I will open a PR to add the keyword soon. Thanks so much for the info!

**Comment by kakirastern** [comment]
PR opened to follow up on this Issue.

**Comment by kakirastern** [comment]
Ready to close as problem has been resolved?

**Comment by agarwalrounak** [comment]
@kakirastern you should write Fixes #[issue_number] in your PR if you are solving the issue in entirety. That way, the issue automatically closes when the PR is merged.

**Comment by kakirastern** [comment]
Thanks, I was experimenting

**Comment by kakirastern** [comment]
We actually confirmed it on Tuesday after merging some files but it was too late for this issue... having been already merged.

**Comment by kakirastern** [comment]
Actually, I think "Closes #..." works as well.

**Comment by pllim** [comment]
>I think "Closes #..." works as well

Yes, it does.

**Comment by kakirastern** [comment]
Think this issue has been dealt with in an earlier PR, so will close it now.
