### ISSUE TITLE
Add kakirastern as author on FITS-cubes tutorials

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#332]
Add @kakirastern as an author for doing a lot of work to bring the FITS-cube tutorial out of quarantine.

**Comment by agarwalrounak** [comment]
I will work on it.

**Comment by kakirastern** [comment]
Hi @agarwalrounak ... Maybe we should wait a bit... since my work is not completed yet I would like to add my name to the Authors list later on when the file is ready for release.

**Comment by kakirastern** [comment]
We have a reduced-size data cube ready to replace the one used originally. That has been done, but the issue of the manner of replacement needs to be discussed in a group context. After that my name should be added.

**Comment by kakirastern** [comment]
Yup, done in PR #347.
