### ISSUE TITLE
The two links at the bottom of tutorials on Learn Astropy website not working

### ISSUE THREAD

**Issue by kakirastern** [astropy/astropy-tutorials#336]
As stated, the two buttons at the bottom of the tutorial pages have faulty links, unlike the two up top, which are working. 

![screenshot 2019-02-26 21 44 50](https://user-images.githubusercontent.com/26264600/53417209-0a683500-3a10-11e9-817a-882df2298c5e.png)

If you link on either the "Download tutorial notebook" or "Interactive tutorial notebook" button, it will return a "404 not found" error page, as:

![screenshot 2019-02-26 21 45 06](https://user-images.githubusercontent.com/26264600/53417316-51562a80-3a10-11e9-8600-25fab7583137.png)

**Comment by mwcraig** [comment]
A little more information (from the [Analyzing UVES Spectroscopy with Astropy](http://learn.astropy.org/rst-tutorials/UVES.html?highlight=filtertutorials) tutorial).

The "Download"/"Interactive" buttons at the top of the page work. The same buttons at the bottom of the notebook fail.

The URLs attached to the buttons are:

+ "Download..." button
    + Top of page: http://learn.astropy.org/_static/UVES/UVES.ipynb
    + Bottom of page: http://learn.astropy.org/_static//.ipynb
+ "Interactive..." button
    + Top of page: https://beta.mybinder.org/v2/gh/astropy/astropy-tutorials/master?filepath=/tutorials/notebooks/UVES/UVES.ipynb
    + Bottom of page: https://beta.mybinder.org/v2/gh/astropy/astropy-tutorials/master?filepath=/tutorials/notebooks//.ipynb

For both buttons at the bottom the `UVES/UVES` part of the path is missing.

**Comment by kakirastern** [comment]
Am tracking down the code block(s) for both of these buttons at the bottom to see if I can open a PR to fix it...
