### ISSUE TITLE
Sometimes the tutorials don't load when going to main tutorials page

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#337]
About 50% of the time, when I go to learn.astropy.org and click "tutorials," the page says "No tutorials found!" until I refresh, and then the tutorials appear. I know @eblur and @kelle have run in to this issue as well. Do you have any idea what could be causing this? I think this is the highest priority bug to work on in the near term!

**Comment by pllim** [comment]
I traced it to most probably

https://github.com/astropy/astropy-tutorials/blob/d3789d7d3ce2c0b95df2a91128d8edb2bc68d97b/tutorials/themes/tutorials-theme/static/searchtools.js#L413

The most stable fix is to find a way to search "locally" instead of relying on HTTPS connection. Unfortunately, I am not familiar enough with the design to suggest more.

**Comment by MananAgarwal** [comment]
Yeah, even I have run into this. I am not sure what exactly is causing this but I feel it's a latency issue. This is slightly hard to debug, as you won't face this issue when debugging on a local server.

**Comment by kakirastern** [comment]
I would like to give it a try and debug if no one else is up to it... Will open a PR within the next few days to attempt a fix.

**Comment by kakirastern** [comment]
That is, only if @MananAgarwal grant me permission to give it a try, since he's been assigned to it originally...

**Comment by MananAgarwal** [comment]
Sure @kakirastern, would love to collaborate with you on this.

**Comment by kakirastern** [comment]
Yup, that would be super cool @MananAgarwal...

**Comment by kakirastern** [comment]
PR #340 opened to fix the issue... Think it is ready for a preliminary review.

**Comment by kakirastern** [comment]
I think a better plan is to merge PR #340 first, then allow me and @MananAgarwal time to continue work on a cross-browser solution to warn of no tutorials when using a filter selection only in PR #344. That would be the best strategy we have now.

**Comment by astrofrog** [comment]
Just wanted to say I ran into this issue today (it happens 100% of the time for me on a first load before refreshing) and I think we really need to fix this as soon as possible - as I noticed today that tutorials.astropy.org now redirects to learn.astropy.org, so there is no way to get the 'old' list of tutorials.

**Comment by kakirastern** [comment]
@adrn You are right about Chrome and Safari... The PR works for all three major browsers including Chrome, Firefox, and Safari, except while you open "learn.astropy.org" via a private window or the incognito mode. In that case it only works for Chrome. Not sure though.
