### ISSUE TITLE
new FITS-cube data cube needs to go on astropy data repo

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#345]
http://www.astropy.org/astropy-tutorials/contributing.html#data-files

**Comment by kakirastern** [comment]
Have worked on it in PR #347. Will need administrative help in moving the reduced data cube `reduced_TAN_C14.fits` to `http://data.astropy.org/tutorials/FITS-cubes/`, before the tutorial path is changed in the FITS-cubes tutorial and then that PR merged.
