### ISSUE TITLE
Can we rid ourselves of Travis?

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#346]
Now that we have both CircleCI and Travis, can we get rid of one? Seems like CircleCI is needed to trigger Giles, but Travis ... ?

@adrn

**Comment by pllim** [comment]
You might have to anyway sooner or later. https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/

**Comment by adrn** [comment]
see #349!
