### ISSUE TITLE
Travis CI is currently disabled

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#349]
The vision for using Travis CI was to have our full testing build matrix done on Travis, and the website build done on Circle CI. But this is currently not implemented, and the Travis builds are consistently failing because of remote connections or timeouts on duplications of the Circle CI tests. So I'm temporarily disabling travis!

**Comment by kakirastern** [comment]
Thanks, @adrn!

**Comment by eteq** [comment]
A development to consider: as part of the spacetelescope/notebooks repo we've built some machinery starting from the astropy-tutorials repo.  Part of that includes streamlining/making more useful the CircleCI machinery for tutorial builds.  So if we try to port that back here (which I would like to see!) maybe we can just leave Travis off and replace with Circle completely?
