### ISSUE TITLE
Small CSS issue with 'Documentation'

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tutorials#351]
When I open learn.astropy.org in Chrome on my Mac the default window size is such that the 'n' in documentation wraps to the next line. If I make the window narrower or wider things get fixed, but the initial view is problematic:

<img width="1155" alt="Screenshot 2019-03-18 at 09 08 44" src="https://user-images.githubusercontent.com/314716/54515881-b93bc900-495d-11e9-9595-dcc73fc2676e.png">

**Comment by kakirastern** [comment]
@astrofrog I have checked on the issue: I cannot produce the issue > 95% of the time unless I minimize my Chrome web browser to a certain size. This is what I'd normally get with my ~13-inch MacBook Air (2015):

![Screenshot 2019-03-30 04 42 33](https://user-images.githubusercontent.com/26264600/55261652-77d4e300-52a6-11e9-8414-aa6cc0d4d020.png)

Could you provide more details about your Mac so this issue can be followed up, such as its size?
