### ISSUE TITLE
Decide how to integrate guide content with learn.astropy.org

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy-tutorials#352]
This is related to #271, which briefly discusses one option for organization of files.

There are a few issues to be resolved:

1. Should we use jupyter-book to render the guides? A VERY roughly example is at https://mwcraig.github.io/ccd-as-book/01-00-Understanding-an-astronomical-CCD-image.html (*please do not give feedback on this yet, there are several issues with it currently, some pretty fundamental*). This is related to...
2. How/where do we want links between related guide pages? Unlike standard one-notebook tutorial the guide has several related notebooks. The question here is less "how do I auto-generate these links" and more "how do we present navigation...links to prev/next? sidebar? breadcrumbs? both?"
3. Should the guides notebooks be more independent so we don't need to worry so much about 1 and 2?

Ping @eteq @adrn as folks on tutorial infrastructure and @kelle FYI

**Comment by adrn** [comment]
I believe this is solved as well.
