### ISSUE TITLE
Data location for CCD guide

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy-tutorials#353]
There are a few 100s of MB of data that will eventually need to be hosted on data.astropy.org. Right now I'm using a mix of local files, downloads from a server on my campus, and downloads from other servers.

**Comment by eteq** [comment]
Do you think these files can be hosted on Zenodo?  @crawfordsm and I have discussed that that *might* be a better long-term plan than data.astropy.org . In principle it's as simple as uploading to zenodo and providing a direct link to the permanent Zenodo location.  This might be a good "beta test" to see if that works well for guides and tutorials?

**Comment by adrn** [comment]
I think this was resolved?
