### ISSUE TITLE
Fix math-mode rst directive conversion to not be picky about spacing

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#357]
This comes out of #338, where I first realized the problem.  The gist is that something that in the notebook looks like this:
```
text text text
$$
math = equation + variable
$$
more text
```
Renders just fine as a equation on its own line, *but* when converted to rst and then to html, it fails because rst directives have to have whitespace around them.  The workaround is to do this:
```
text text text

$$
math = equation + variable
$$

more text
```

But as #338 demonstrates this is not at all intuitive given that it all works fine in the notebook.  So the fix would be to convince the nb->rst conversion stage to add an extra set of newlines around the ``math`` directive.

@adrn, do you know offhand if this requires an upstream fix in nbconvert or if we can do it ourselves here?

**Comment by adrn** [comment]
Not using sphinx anymore, so I think this is not relevant?
