### ISSUE TITLE
Make it so that CI infrastructure continues even if an unrelated notebook fails

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#358]
In the current CI machinery, if a notebook fails the tests stop. This causes issues like astropy/astroquery#1436 where a single failing notebook can prevent tests from running on a PR that *doesn't touch that notebook*. A relatively straighttforward fix would be to adjust the build machinery so that the infrastructure instead ran the notebooks anyway regardless of whether an earlier one fails.

An alternative (although more extreme) approach might be to *only* run the notebook that a PR is about (if it's limited to one notebook).  That would avoid the failure problem entirely in the scenario above.

**Comment by eteq** [comment]
Not that the "an alternative" is the direction I have been hoping to go in https://github.com/eteq/nbpages, so if we were to switch to using that as the underlying infrastructure it might solve this.

**Comment by bsipocz** [comment]
In the alternative solution I would strongly advise to run the whole suite from cron nevertheless with someone actually keeping an eye on the results whether there are any failures. Otherwise it will be a huge firefighting mission to fix stuff when actual users report them.

**Comment by adrn** [comment]
Now that we're using `nbcollection`, this is no longer relevant.
