### ISSUE TITLE
Learn Astropy website won't update due to FITS files being copied to gh-pages

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-tutorials#361]
Please see the latest website build (click on "Push to gh-pages branch"):
https://circleci.com/gh/astropy/astropy-tutorials/535

For some reason, the fits files from the FITS cubes tutorial are being pushed to gh-pages. I'm not sure why, but this is preventing our website from being updated with the new tutorials.

Can we troubleshoot why this is happening and prevent it?

**Comment by MananAgarwal** [comment]
As we are hosting the website from the gh-pages, we need to push the built files to this branch. It seems like one of the FITS files from FITS Cubes tutorial is more than 100MB in size, which is [not supported](https://help.github.com/en/articles/working-with-large-files) by GitHub. 
I think we can fix this by using **[Git Large File Storage](https://git-lfs.github.com/)**, a Git extension to version large files. We'll need to manage only the large files using this and will have to add it in the Sphinx build process. As I am not very familiar with the Sphinx build process, @adrn should be able to tell us how feasible this solution is.

**Comment by adrn** [comment]
Argh, why didn't that PR fix this?!

**Comment by adrn** [comment]
OK now it's fixed!
