### ISSUE TITLE
The term "filterTutorials" still showing in search field on "search.html" page

### ISSUE THREAD

**Issue by kakirastern** [astropy/astropy-tutorials#401]
To follow up on #304. 

I have a feeling that this issue is indicative of a bug plaguing the Learn Astropy website in a way that warrants further investigation. 

Screenshot captured on September 10th, 2019 (HKT) on Chrome:

<img width="1428" alt="Screenshot 2019-09-10 01 06 48" src="https://user-images.githubusercontent.com/26264600/64551395-805a3b00-d367-11e9-9c89-fdae2e072b6e.png">

It is interesting, because after you have searched for some search terms the field is showing the desired "Search the universe of Astropy" as coded in the "navbar.html" instead. See say if we changed the URL to "http://learn.astropy.org/search.html?q=scipy.integrate#" and then delete the original search term from the search field:

<img width="1277" alt="Screenshot 2019-09-10 01 11 10" src="https://user-images.githubusercontent.com/26264600/64551589-ef379400-d367-11e9-83f3-e64856896730.png">

**Comment by adrn** [comment]
Closing in anticipation of new website launch
