### ISSUE TITLE
Local build error

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy-tutorials#409]
I'm working on a new tutorial for astropy-tutorials and my local environment fails to build the webpage when I run `make html` (following these [instructions](http://learn.astropy.org/dev.html#dev-page)), with the following error: 
```
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'astropy.stsci.edu'. (_ssl.c:1056)>
```
Is this familiar to anyone?

**Comment by pllim** [comment]
I am guessing it is coming from `astroquery`? Please upgrade your `astroquery` or even `astropy`.

**Comment by bmorris3** [comment]
That fixed it, thanks @pllim!
