### ISSUE TITLE
Color-excess tutorial doesn't run unless synphot is installed

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#416]
When using Binder to launch the color-excess tutorial, the first line doesn't run because `'ModuleNotFoundError:` No module named 'synphot'

Adding `pip install synphot` fixes the issue but I don't understand why it's not already installed because it's in the requirements.txt.

I also notice that there are specific install instructions in the Summary section. Should those instead by executable lines and/or included in the requirements.txt instead?

**Comment by pllim** [comment]
The `conda` command can be replaced by `pip`, so `requirements.txt` should have worked.
