### ISSUE TITLE
Build dependencies are not listed

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tutorials#445]
The dev docs needs a subsection on the required dependencies for building/testing the notebook-html conversion. 

Neither `sphinx_bootstrap_theme` nor `pandoc` nor `nbconvert` are mentioned in the dev docs as required dependency.

**Comment by kakirastern** [comment]
Is it okay for me to take the issue on?

**Comment by bsipocz** [comment]
I deliberately left it as a novice issue for a newcomer (fixing it would have taken the same time as opening the issue). But of course you can take it if you like

**Comment by kakirastern** [comment]
I am waiting for a bit because the Learn Astropy site is being revamped

**Comment by embray** [comment]
I noticed this as well.  There are several other things that go wrong when I try to just build the site locally from my usual astropy virtualenv.

**Comment by embray** [comment]
Additionally, the `.travis.yml` installs nbconvert from git, but I don't think that's necessary any longer.  According to git that line was added in 2017, and nbconvert has had many releases since then.
