### ISSUE TITLE
Uves tutorial rendering error

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-tutorials#448]
There are some formatting errors in the UVES tutorial. Most don't look good but are not critical (external links not showing up), but this one is critical:
![image](https://user-images.githubusercontent.com/498688/80851370-505df180-8bef-11ea-92c1-b85941b1506d.png)
There definitely needs to be a line break after the import statement. Curiously, there is when I look the rendered notebook on github. So there must be something wrong with the way learn.astropy.org renders notebooks.

**Comment by adrn** [comment]
This was a bug with the way the multi-line code was specified - I believe there need to be line breaks after / before the ```
