### ISSUE TITLE
error in ellipse.fit_image

### ISSUE THREAD

**Issue by oglesbylily** [astropy/astropy-tutorials#452]
I'm trying to run the tutorial https://github.com/astropy/photutils-datasets/blob/master/notebooks/isophote/isophote_example1.ipynb. However when I run the command isolist = ellipse.fit_image(), I get the following error: isophote = isophote_list[-1]. IndexError: list index out of range. 
I am only pasting the commands provided from the tutorial. Could this be a problem with my python setup? I am running python 3.8 and PyCharm on a Mac book pro. 
Thanks for any help.

**Comment by kakirastern** [comment]
Hi @oglesbylily I tried running the code on Jupyter Lab using `python 3.8` on my MacBook Pro, but everything seemed to be running smoothly. Let me try `PyCharm` as well to see if I could reproduce the error.

**Comment by kakirastern** [comment]
I have tried running the same notebook on PyCharm with the `jupyter` package installed, and seems everything is fine as far as I can tell. The following is a screenshot including the printout of the `isolist` variable in the lower left corner pane:

<img width="1440" alt="Screenshot 2020-07-05 20 05 19" src="https://user-images.githubusercontent.com/26264600/86532256-16fd7700-befb-11ea-81fb-c6aff5153c56.png">

**Comment by kakirastern** [comment]
The way I run the notebook is via `Jupyter Actions` accessible in PyCharm.

**Comment by oglesbylily** [comment]
Thank you so much for getting back to me so quickly. I've installed Jupyter notebook but I am still getting the same error. Please see the screen snapshot below. As you can see, I am very new at this. 
![image](https://user-images.githubusercontent.com/67838999/86540618-a8e58f80-bebb-11ea-895b-feba0c805987.png)

**Comment by kakirastern** [comment]
Hi @oglesbylily From your screenshot I can tell you are missing a dependency of `photutils` called `scipy`, which you can install either with [pip](https://pypi.org/project/scipy/) or [conda](https://anaconda.org/anaconda/scipy). Try installing that first and run the notebook again. If the problem persist, do let us know and we will sort it out for you.

**Comment by oglesbylily** [comment]
Thank you so much --  it worked perfectly! I really appreciate all your help.

**Comment by kakirastern** [comment]
You are welcome! I am glad to be of help.
