### ISSUE TITLE
Search: using deprecated API (https://readthedocs.org/api/v2/docsearch/)

### ISSUE THREAD

**Issue by stsewd** [astropy/astropy-tutorials#459]
Hi! I work at Read the Docs, I'm reaching to you since we are in the process of removing this undocumented API (https://readthedocs.org/api/v2/docsearch). We are replacing it with https://docs.readthedocs.io/en/stable/server-side-search.html#api 

I noticed you are using the old API at https://github.com/astropy/astropy-tutorials/blob/21968ff28eaf1c72f9d022ceb788bb2fc464022e/tutorials/themes/tutorials-theme/static/searchtools.js#L419

You can check how we use it at https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/core/static-src/core/js/doc-embed/search.js and https://github.com/readthedocs/readthedocs-sphinx-search/blob/master/sphinx_search/static/js/rtd_sphinx_search.js

**Comment by pllim** [comment]
Thank you for the notice! cc @adrn and @embray

**Comment by embray** [comment]
@stsewd Thanks.  I'll work on this if no one else gets to it first (I need to be added as a collaborator on this project to assign myself).

**Comment by kakirastern** [comment]
Hey @embray Just assigned the issue to you

**Comment by pllim** [comment]
@embray , I have temporarily given you Triage access -- is that enough to assign self? Unfortunately, I cannot add you to one of the teams, maybe @astrofrog can.

p.s. The admin team has some names of inactive contributors. It is scary that they have admin access. I think the team needs some pruning.

**Comment by stsewd** [comment]
Hi everyone, we are removing the old endpoint tomorrow as we are behind schedule to update to a supported version of ES. We are in the 6.x series (already EOL), and we need this change to update to the latest 7.x. Let me know if there is anything I can help you with.

**Comment by pllim** [comment]
Thanks, @stsewd ! I started a draft PR over at #462 . Your advise, should you choose to provide it, would be greatly appreciated.

**Comment by pllim** [comment]
Maybe this is biting us now. I see that the RTD webhook is broken.

**Comment by adrn** [comment]
New front-end deploy is imminent (cc @jonathansick)! When I find a few hours of time, I'm planning to replace the current site with a simple "new site coming soon" + static list of links to rendered tutorials.

**Comment by pllim** [comment]
I hope you add a 1990s 🚧 GIF, for old time's sake!

**Comment by adrn** [comment]
<img src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/underconstruction.gif?raw=true"/><img src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/underconstruction.gif?raw=true"/><img width=42px src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/siren.gif?raw=true"/><img width=42p src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/siren.gif?raw=trueWebsite"/> Website coming soon! <img width=42p src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/siren.gif?raw=trueWebsite"/><img width=42p src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/siren.gif?raw=trueWebsite"/><img src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/underconstruction.gif?raw=true"/><img src="https://github.com/davidwhogg/AstroWorse/blob/master/astroworse/static/images/underconstruction.gif?raw=true"/>
