### ISSUE TITLE
Error in FITS-cubes.ipynb

### ISSUE THREAD

**Issue by embray** [astropy/astropy-tutorials#463]
When processing the FITS-cubes.ipynb notebook I'm getting an error from astroquery:

```
# Query for Herschel data in a 1 degree radius around the SMC
result = ESASky.query_region_maps('SMC', radius=1*u.deg, missions='Herschel')

print(result)
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-3cb6373bfea7> in <module>
      1 # Query for Herschel data in a 1 degree radius around the SMC
----> 2 result = ESASky.query_region_maps('SMC', radius=1*u.deg, missions='Herschel')
      3 
      4 print(result)

~/.virtualenvs/astropy/lib/python3.6/site-packages/astroquery/esasky/core.py in query_region_maps(self, position, radius, missions, get_query_payload, cache)
    236         self._store_query_result_maps(query_result, sanitized_missions,
    237                                       coordinates, sanitized_radius,
--> 238                                       get_query_payload, cache)
    239 
    240         if (get_query_payload):

~/.virtualenvs/astropy/lib/python3.6/site-packages/astroquery/esasky/core.py in _store_query_result_maps(self, query_result, missions, coordinates, radius, get_query_payload, cache)
    768             mission_table = self._query_region_maps(coordinates, radius,
    769                                                     mission, get_query_payload,
--> 770                                                     cache)
    771             if (len(mission_table) > 0):
    772                 query_result[mission.upper()] = mission_table

~/.virtualenvs/astropy/lib/python3.6/site-packages/astroquery/esasky/core.py in _query_region_maps(self, coordinates, radius, observation_name, get_query_payload, cache)
    682         query = (
    683             self._build_observation_query(coordinates, radius,
--> 684                                           self._find_observation_parameters(observation_tap_name)))
    685         request_payload = self._create_request_payload(query)
    686         if (get_query_payload):

~/.virtualenvs/astropy/lib/python3.6/site-packages/astroquery/esasky/core.py in _build_observation_query(self, coordinates, radius, json)
    711         from_query = " FROM {}".format(json[self.__TAP_TABLE_STRING])
    712         if (radiusDeg != 0 or json[self.__IS_SURVEY_MISSION_STRING]):
--> 713             if (json[self.__IS_SURVEY_MISSION_STRING]):
    714                 where_query = (" WHERE 1=CONTAINS(pos, CIRCLE('ICRS', {}, {}, {}));".
    715                                format(ra, dec, radiusDeg))

KeyError: 'isSurveyMission'
KeyError: 'isSurveyMission'
```

Not sure what that's about or how best to fix it.

**Comment by pllim** [comment]
Which astroquery version? Be sure to grab the latest pre-release from PyPI.
`pip install astroquery --pre --upgrade`

**Comment by pllim** [comment]
If you still have problem, could be that API is outdated or something, and try open issue over at `astroquery`. Hope this helps!

**Comment by embray** [comment]
I didn't get the pre-release.  Was using 0.4.1 which was the default from the `pip-requirements.txt` which specifies `astroquery>=0.3.7`.  This might be a problem related to #445

**Comment by pllim** [comment]
Using stable astroquery won't do because they have to fix for upstream changes on demand, so they opted for "rolling release." I would recommend `--pre`.

**Comment by embray** [comment]
Using the latest pre-release didn't work.  The notebook in question was last updated in March 2020 so it shouldn't require the bleeding edge anyways.

**Comment by pllim** [comment]
What about dev? (Just in case)

**Comment by embray** [comment]
It looks like it has the same issue.  I'll open an issue against astroquery...

**Comment by embray** [comment]
FWIW the issue can be reproduced simply by

```python
>>> from astropy import units as u
>>> from astroquery.esasky import ESASky
>>> ESASky.query_region_maps('SMC', radius=1*u.deg, missions='Herschel')
```

ISTM some piece of metadata that's expected to exist in the query results does not, and the code doesn't handle it being missing.

**Comment by pllim** [comment]
Thanks for checking. :(

**Comment by embray** [comment]
After installing astroquery from source and applying my workaround, the rest of the notebook executes successfully, so we can close this once astropy-tutorials is building with an appropriate version of astroquery.

**Comment by RobinThomas95** [comment]
Hi, I am encountering the aforementioned issue while using astroquery.ESASky queries. Can you guide me on a possible solution? Thank you

**Comment by embray** [comment]
@RobinThomas95 This is fixed in the development version of astroquery and the relevant issue is here: astropy/astroquery#1856

You can install the latest development version of astroquery if you need this fixed.  Will you need help on how to do that?

**Comment by RobinThomas95** [comment]
@embray It'd be helpful if you could guide me on how to install the dev version of astroquery, Thank You

**Comment by embray** [comment]
@RobinThomas95 How are you installing astroquery in the first place?

**Comment by RobinThomas95** [comment]
@embray I'm using pip install astroquery to install the package

**Comment by embray** [comment]
@RobinThomas95 Ok great, in that case you can `pip install --pre astroquery` to install the latest pre-release, which I believe includes this fix.

**Comment by RobinThomas95** [comment]
@embray Sorry for the late reply. I tried pip installing as you advised, restarted the Jupyter kernel that I'm using and then ran the astroquery. The error still persists.

**Comment by pllim** [comment]
Might have to install from source `pip install git+https://github.com/astropy/astroquery`. Just to be safe, do a `pip uninstall astroquery` until it complains it cannot find `astroquery` **first** before you install from source.

**Comment by RobinThomas95** [comment]
@pllim @embray Thank you so much, guys. The solution suggested by @pllim worked out for me. :)

**Comment by HugoDelgado** [comment]
Im getting errors trying to install with Conda, pip or even the git source option.

**Comment by pllim** [comment]
This particular issue from original post is already resolved. If you encounter problems with our tutorials, please open new issue with all the necessary info (versions, OS, environment, traceback). Thanks!
