### ISSUE TITLE
Post Install instructions for M1 Mac

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#474]
I worked with some folks to put together some instructions for how to get a new mac (with new chip) setup to work with Astropy. we should post this somewhere, but I'm not exactly sure how.  It's important to note that this document will go out-of-date quickly, so I would recommend we keep it as a google doc (or something similar) to convey it's transient nature.
https://docs.google.com/document/d/1SqrXBNY4NCBJ1NyCpcLvaQkEtD55tgE26Eg_qdDs618/edit#

**Comment by adrn** [comment]
I recently got an M1 mac and didn't have to follow any special instructions to set it up (it was the same as I've done on any other mac I've had). Is it possible this is now obsolete because packaging has caught up and made it simple again?

**Comment by kelle** [comment]
This doesn't seem to be needed anymore.
