### ISSUE TITLE
color-excess tutorial is failing

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#481]
See, e.g., https://app.circleci.com/pipelines/github/astropy/astropy-tutorials/106/workflows/16a549a0-38a4-4356-b1c2-d9688590e408/jobs/791

**Comment by pllim** [comment]
Looks like MAST -- @ceb8, any ideas?

```python
obsids = ['3000022829']
dataProductsByID = Observations.get_product_list(obsids)
manifest = Observations.download_products(dataProductsByID)
```

**Comment by ceb8** [comment]
It seems like that obsid is not valid anymore. Possibly with the latest CAOM upgrade. Someone who knows what the observation in question is should update the obsid, or even better, make it not hard coded.

**Comment by stephtdouglas** [comment]
I can try to take a look tomorrow or Friday, but I think @krislars (who I can't seem to tag) was the original author. I helped with minor updates to the existing tutorial.

**Comment by krislars** [comment]
Here I am!  @stephtdouglas, the tag worked.  I can take a look over the weekend.

**Comment by krislars** [comment]
I think that I fixed the MAST observation ID.  And I also think that I initiated a pull request?  I'm rusty on the protocol.  As the original author of this tutorial, I can see several ways to improve it now, but this small change should fix the problem for now.
