### ISSUE TITLE
color_excess tutorial is failing because it can't access an STScI page

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#514]
See an example here:
https://github.com/astropy/astropy-tutorials/runs/4662944242?check_suite_focus=true

cc @krislars

**Comment by pllim** [comment]
Whoops. IT made me shut down that domain. Please replace "cdbs" with "trds"; e.g., http://ssb.stsci.edu/trds/calspec/alpha_lyr_stis_008.fits
