### ISSUE TITLE
In PRs, only execute notebooks that have been modified

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#519]
We have discussed this idea for a while, but we should implement functionality such that in a pull request, nbcollection only executes notebooks that have been modified. This will significantly reduce the CI headaches we have in PRs! If we do this, we should add an optional label that would trigger executing all notebooks, and add a weekly cron job that executes all notebooks.

This could either be implemented here with bash scripts that use git commands to get the list of modified files and only passes those names to nbcollection for execution. Or, we could add support for this in nbcollection itself.

**Comment by jonathansick** [comment]
Related issue with a different approach, but not necessarily better: https://github.com/astropy/astropy-tutorials/issues/461
