### ISSUE TITLE
Incorrect derivatives in User-Defined-Model tutorial

### ISSUE THREAD

**Issue by EdBehn** [astropy/astropy-tutorials#562]
I believe that I have have found a mathematical error in the User-Defined-Model tutorial (Full custom model section). 

The derivatives should be 

<code>d_a = np.sin(b\*x+c)</code>

and 

<code>d_c = a\*np.cos(b\*x+c)</code>

**Comment by kelle** [comment]
@rkiman , could you take a look at this?

**Comment by rkiman** [comment]
@kelle I fixed this last year. The issue can be closed.
