### ISSUE TITLE
Formatting issue on how-to-contribute page

### ISSUE THREAD

**Issue by keflavich** [astropy/astropy-tutorials#598]
https://learn.astropy.org/contributing/how-to-contribute

<img width="1029" alt="image" src="https://github.com/astropy/astropy-tutorials/assets/143715/e496a18a-8c1e-4638-9718-efa45d912623">

I can't figure out where this page is generated, though - where do I submit a PR?

**Comment by jeffjennings** [comment]
(I fixed it just now, but the learn website pages are generated at https://github.com/astropy/learn-astropy.)
