### ISSUE TITLE
Fix broken build process - implement `nox`? 

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-tutorials#601]
The website is currently not building successfully.  It likely needs some significant attention in order to fix.

One big problem: notebooks have competing requirements.  

Proposal:  each notebook needs it’s own requirements.txt and environment.  compile the notebooks. and  then keep the HTML build.  Possible tool = `nox` .

**Comment by jeffjennings** [comment]
The `build.yml` workflow is now [failing](https://github.com/astropy/astropy-tutorials/actions/runs/11070297000/job/30759676150) due to 'Bad credentials' - I'm guessing the `secrets.DISPATCH_GITHUB_TOKEN` in this repo expired and needs to be re-generated. I don't have permissions to edit the repo secrets so can't do this - @kelle or @adrn, could you?

**Comment by adrn** [comment]
I don't have admin access to the repo so I can't control secrets. @pllim ?

**Comment by pllim** [comment]
I don't use nox . Where are the instructions to regenerate such a token? Thanks!

**Comment by jeffjennings** [comment]
To generate a new token, from the repo on github, go to 'Settings' at the top of the page, then 'Secrets and Variables' in the left panel, then 'Actions' --> 'New repository secret'; name it DISPATCH_GITHUB_TOKEN. For the secret value (the token), I'm not sure how astropy handles token permissions, but I believe what's needed is a personal access token as described [here](https://github.com/peter-evans/repository-dispatch?tab=readme-ov-file#token). I think it needs read/write access in both the _astropy-tutorials_ repo and the _learn-astropy_ repo.

**Comment by jeffjennings** [comment]
Just to note here in response to Kelle's question about using `nox`; we're instead setting up the environment for each notebook using the `Makefile`.

**Comment by pllim** [comment]
Re: token -- I need time to investigate if fine grained PAT is even possible in org level but not sure when. Has this workflow ever succeeded before? If yes, how did you set it up prior?

**Comment by jeffjennings** [comment]
There might be a different way it's done in astropy, sorry I'm not sure. The workflow did used succeed >1 year ago, but I think a former contractor may have set it up, or maybe @kelle knows more.

**Comment by pllim** [comment]
@jeffjennings , maybe you can play around with that over at the CCA org first because I cannot figure out how to do this for Astropy org. I can only create PAT from my own account, but from there, I cannot specific Astropy org repos. The docs I can find are not very clear on this. Please let me know if you have success. Thanks!

**Comment by kelle** [comment]
I've made a token and DM'd you both in Slack.

**Comment by jeffjennings** [comment]
For future reference, the [Dispatch Learn Astropy](https://github.com/astropy/astropy-tutorials/blob/fd4d29bed038c26e6e0b2febf8e2118126866e8d/.github/workflows/build.yml#L48C15-L48C48) step in the build workflow was failing. It now passes after Kelle created a new fine-grained personal access token with write/read access to the contents of this repo and [astropy-learn](https://github.com/astropy/learn-astropy/pull/82), following the instructions [here](https://github.com/peter-evans/repository-dispatch). 

I've set #606 to close this issue, as that solves the problem Kelle mentions at the top of this issue: individual notebooks can have competing (version) dependencies.
