### ISSUE TITLE
Improve fonts in CSS

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tutorials#63]
At the moment, the font sizes look a little inconsistent in the tutorials:

![screen shot 2014-06-12 at 16 44 59](https://cloud.githubusercontent.com/assets/314716/3259062/28d91cba-f240-11e3-90df-fa4424c062f1.png)

I think it would be good to have someone go though and try and polish up the CSS a little to make font sizes more consistent, and improve spacing, etc.

Maybe you could ask on the astropy-dev list if any CSS experts would be interested in helping?

**Comment by adrn** [comment]
@astrofrog the style is a little different now with Jupyter notebooks, so interested to see if you still have comments, but can you clarify exactly what you'd like to see improved?

**Comment by foowhiz** [comment]
@astrofrog Hi, I'm new to AstroPy, and I think I might be able to contribute to this issue... I'm no expert in CSS, but I do know enough to be able to change fonts...

**Comment by adrn** [comment]
I think they are fine (now they are consistent with the Astropy documentation), but please open a PR if you want to change them.
