### ISSUE TITLE
Add a script for checking that requirements are met for running tutorial

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropy-tutorials#64]
For the SciPy tutorials they asked as to prepare a script to verify that the required packages were available to run the tutorial.  The result was:
https://github.com/astropy/astropy4scipy2014/blob/master/check_env.py

This was thrown together very quickly, but something along these lines might be a good idea for the Astropy tutorials as well.  It might make sense to have a `check_env` script for each tutorial since the requirements for different tutorials might be different.

Note that we uncovered an apparent bug in `distutils.version.LooseVersion` in that it fails to support comparison of versions that contain strings (like `dev`) in Python 3.  Hence the current `check_env.py` script just does a string comparison of versions, but this would need to be fixed.

**Comment by amanXCalibre** [comment]
Hey @taldcroft  does this pull request fix this issue ?
https://github.com/astropy/astropy-tutorials/pull/83

**Comment by adrn** [comment]
This can now be done with setuptools `pkg_resources` with the one-liner:
```bash
python -c "import pkg_resources; pkg_resources.require(open('pip-requirements.txt', mode='r')); print('Your environment is all set!')"
```
Maybe we should add this to our readme?
