### ISSUE TITLE
Bug with RA increasing to the right

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tutorials#67]
This plot in Quantities is wrong:

![unknown](https://cloud.githubusercontent.com/assets/314716/3501932/92dd56f0-061b-11e4-9a56-2d866db2e906.png)

The RA should increase to the left! Same goes with the plot-catalog tutorial:

![unknown-1](https://cloud.githubusercontent.com/assets/314716/3501940/a438f580-061b-11e4-8281-a6393bf9c85a.png)

**Comment by adrn** [comment]
This was addressed with #70
