### ISSUE TITLE
Set up automatic travis-based build of the tutorials page

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#72]
Right now someone has to manually run the deploy script to generate the gh-pages branch.  We should be able to use travis to install astropy from conda, use that to build the tutorials, and then post them to GitHub pages.  An example of a ruby project that does something like that is [here](http://awestruct.org/auto-deploy-to-github-pages/)... I'm pretty sure we could do something fairly similar.

@adrn or @astrofrog, was there a specific reason we didn't do this previously, or was it just that we didn't know how?

**Comment by mwcraig** [comment]
Does this essentially consist of running the deploy script from travis? If yes, can take a shot at it this week.

**Comment by eteq** [comment]
This was actually done a while back.  Not sure exactly when it was finished, but it seems to be running, so closing this issue!

**Comment by bsipocz** [comment]
@pllim - I'm afraid our dreaded moment just came, @astropy-bot has become fully sentient 😄

**Comment by pllim** [comment]
😱

**Comment by pllim** [comment]
I thought only @astrobot was getting there, but now we also have @astropy-bot!

**Comment by bsipocz** [comment]
ahh, right. There are two bots then, I wondered how @kelle got hold of it (assuming it was @astrobot).

**Comment by bsipocz** [comment]
@eteq - To be ontopic I think this was done by you in #102

**Comment by adrn** [comment]
Weird, I did do this with someone at pyastro, but I don't remember working with any cylons...

**Comment by bsipocz** [comment]
wasn't that with the example-gallery in the core docs?

**Comment by adrn** [comment]
:man_facepalming: yes...you're right! @eteq solved this in #102
