### ISSUE TITLE
Add content to VO conesearch tutorial

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-tutorials#82]
Right now, the tutorial reads a bit like documentation and is primarily just focused on conesearch (and some Quantity). I don't think it would be much work to add a few things to highlight synergies with other astropy subpackages and make it feel more like a workflow. 

A few ideas:
- Add a section where you write out a catalog to disk using `astropy.table`
- Query a catalog and turn it into a Latex table
- Use aplpy and overplot circles marking known sources with some constraint over an image
- Use an SDSS query to get positions for sources, then query the SDSS SAS (http://dr12.sdss3.org/) to get back a few spectra to plot

**Comment by adrn** [comment]
This also needs a `description` in the metadata of the notebook.

**Comment by pllim** [comment]
I moved Cone Search to Astroquery, so should I completely remove Cone Search tutorial from here when it is deprecated from Astropy (possibly in v2.0)?

**Comment by adrn** [comment]
I think it's fine to have tutorials that cover affiliated packages, so if you can stand it, maybe you could just update the tutorial?

**Comment by pllim** [comment]
Sure. I'll do that after Astroquery 0.3.5 is released.

**Comment by pllim** [comment]
Huh... Why is this closed? Is #116 no longer necessary?

**Comment by adrn** [comment]
Hm, I guess it was a hasty click on my part!

**Comment by pllim** [comment]
Oh... What are the remaining issues that #116 failed to address?

**Comment by pllim** [comment]
Is this still an issue?

**Comment by adrn** [comment]
No!
