### ISSUE TITLE
Improve FITS header tutorial

### ISSUE THREAD

**Issue by embray** [astropy/astropy-tutorials#89]
Over in [this comment](https://github.com/astropy/astropy/issues/3661#issuecomment-89355289) I griped about the current state of the FITS-Header tutorial.  However, I was pretty vague as to what I don't like about it.  And actually, upon a second look, I don't have as much problem as I thought I did.  As a very introductory tutorial I think it's fine to promote the "convenience functions", since this will be a lot easier for many newcomers to wrap their heads around.

I think I would just like to make a few slight tweaks, and also to at least _mention_ the more "preferred" object-oriented interface, with appropriate links to the more advanced docs?

**Comment by kelle** [comment]
Yes, please do. I have no idea what the "preferred" object-oriented interface is!

**Comment by algerdnazgul** [comment]
Any progress?

**Comment by embray** [comment]
Unfortunately I no longer have a lot of time to spend on Astropy (at least not on a volunteer basis), but I'd gladly provide guidance to anyone interested in working on this.

**Comment by algerdnazgul** [comment]
Bad news :(
Choose the next one immortal highlander with needed experience in project.

**Comment by pllim** [comment]
@embray , send me a list of things to edit and I'll give it a go. Thanks!
