### ISSUE TITLE
Set up continuous integration for testing?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tutorials#91]
Inspired by a discussion on the Facebook Python in Astronomy group, I was wondering if we can set up Travis to run pytest-ipynb (https://pypi.python.org/pypi/pytest-ipynb) on the notebooks to make sure they don't break with astropy updates?

**Comment by adrn** [comment]
How would you feel about a simpler version (better than nothing): #92 sets up travis to just check that the notebooks run, but doesn't provide detailed errors like pytest-ipynb...

**Comment by eteq** [comment]
I'm closing this on the thoery that #92 answered it... can always make a new issue for pytest-ipynb if we think its warrented
