### ISSUE TITLE
Fix up redshift plot tutorial

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tutorials#94]
As discussed in #85, there were some issued uncovered with the cosmology plotting tutorial after it was merged.  @nhmc, are you still planning to do update this?  It looks to me look the outstanding issues are:

- [x] Address the problem of the two different cosmology axes not matching, perhaps by demonstrating the current version as a "gotcha".
- [x] change the name to redshift_plot or something similar (unless others are against that - this was my suggestion in #85)
- [x] While testing this locally (via ``python prepare_deploy.py run convert`` after setting "published" to true on this tutorial), the first image comes out as a broken link. I think this is because nbconvert doesn't copy over images that aren't embedded in the notebook.  @adrn, do you know how to make this happen?  Alternatively, a cell saying ``IPython.display('image.png')`` will embed the image in the notebook, and that will copy over correctly.
- [x] Change the "published" marker from false to true (I set it to false until we can address this).

**Comment by nhmc** [comment]
Yes, I'll take care of this in the next couple of days.  Thanks for the
reminder.

Neil

**Comment by eteq** [comment]
All fixed in #95, so closing!
